var reprompt_callback=null,reprompt_error_callback=null;g_fixpbkdf2=!0;var login_submitted=!1;
function do_submit(){if(login_submitted)return!1;login_submitted=!0;var a=fix_username(document.getElementById("u").value),e=document.getElementById("p").value;document.getElementById("p").value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";var f=get_key_iterations(a);getBG().make_lp_key_hash_iterations(a,e,f,function(d,c){document.getElementById("p").blur();if(null!=reprompt_callback){var b=getBG();if(d==b.g_local_key){var g=0;document.getElementById("donotrepromptfor").checked&&
(g=document.getElementById("donotrepromptforsecs").value);b.lpPutUserPref("reprompttime",g);b.lpWriteAllPrefs();b.set_last_reprompt_time();reprompt_error_callback=null;b.select_selectedtabid();reprompt_callback();setTimeout(function(){window.close()},0)}else alert(gs("Invalid Password.")),setTimeout(function(){closePop()},0)}else(b=getBG())?(document.getElementById("rememberpassword").checked||(document.getElementById("p").value=""),b.g_manual_login=!0,b.LP_do_login(a,e,document.getElementById("rememberemail").checked,
document.getElementById("rememberpassword").checked,null,document.getElementById("showvault").checked,d,c),reprompt_error_callback=null,e="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",setTimeout(function(){closePop()},0)):alert(gs("Can't find hidden LastPass window"))});return!1}var passwords=[];
function load(a){try{var e="undefined"!=typeof chrome&&("undefined"!=typeof chrome.runtime||"undefined"!=typeof chrome.extension);if(!e&&!a&&("undefined"==typeof safari||"undefined"==typeof safari.extension.globalPage))get_data("login",function(){load(!0)});else{if(e){var f=window.getComputedStyle(document.body,null);100>parseInt(f.width)&&(document.body.style.minWidth="810px",document.body.style.minHeight="333px")}document.getElementById("screenkeyboard").title=gs("Screen Keyboard");getBG().LPISLOC&&
(document.getElementById("forgotcontainer").style.display=document.getElementById("screenkeyboardcontainer").style.display=document.getElementById("createaccountcontainer").style.display="none");getBG().g_hidecreate&&(document.getElementById("createaccountcontainer").style.display="none");if(getBG().g_hidevault||getBG().g_hideshowvault)document.getElementById("showvaultrow").style.display="none";getBG().g_hidescreenkeyboard&&(document.getElementById("screenkeyboardcontainer").style.display="none");
var d=getBG();can_chrome_do_math()||d.openURL(getchromeurl("mathfail.html"));if(null!=d.g_reprompt_callback){reprompt_callback=d.g_reprompt_callback;d.g_reprompt_callback=null;reprompt_error_callback=d.g_reprompt_error_callback;d.g_reprompt_error_callback=null;document.getElementById("reprompttext").style.display="";document.getElementById("deleteicon").style.display="none";document.getElementById("rememberemailrow").style.display="none";document.getElementById("rememberpasswordrow").style.display=
"none";document.getElementById("showvaultrow").style.display="none";document.getElementById("donotrepromptforrow").style.display="";document.getElementById("screenkeyboardcontainer").style.display="none";document.getElementById("forgotcontainer").style.display="none";document.getElementById("u").value=d.g_username;document.getElementById("u").disabled=!0;var c=d.lpGetPref("reprompttime",0);document.getElementById("donotrepromptfor").checked=0<c;document.getElementById("donotrepromptforsecs").value=
c;document.getElementById("p").focus();document.getElementById("links").style.display="none";getBG().can_allow_reprompt_skip()||(document.getElementById("donotrepromptfor").checked=!1,document.getElementById("donotrepromptfor").disabled=!0,document.getElementById("donotrepromptforsecs").disabled=!0);document.getElementById("logintitletxt").innerHTML="";setTimeout(function(){document.getElementById("p").focus()},50)}else{var b=d.lpGetPref("rememberemail",1),g=d.lpGetPref("rememberpassword",-1),h=d.lpGetPref("showvault",
-1);document.getElementById("rememberemail").checked=1==b?!0:!1;document.getElementById("rememberpassword").checked=1==g?!0:!1;document.getElementById("showvault").checked=1==h?!0:!1;getBG().g_db_transaction_tested=getBG().g_db_transaction_worked=!1;populate_usernames()}}}catch(j){console_log(j.message)}}window.addEventListener("keydown",function(a){handle_keydown(a)},!1);
function populate_usernames(){if(document.getElementById("u")){var a=opendb();a||(a=opendb());createSavedLoginsTable(a);a?(a.transaction(function(a){getBG().g_db_transaction_tested=getBG().g_db_transaction_worked=!0;a.executeSql("SELECT * FROM LastPassSavedLogins2 order by last_login desc",[],function(a,d){for(var c=[],b=0;b<d.rows.length;b++)c[b]=d.rows.item(b).username,passwords[c[b]]=d.rows.item(b).password,1==d.rows.item(b)["protected"]?function(a,b){getBG().unprotect_data(b,!1,function(c){passwords[a]=
c;document.getElementById("p").value==b&&(document.getElementById("p").value=c)})}(c[b],passwords[c[b]]):2==d.rows.item(b)["protected"]&&(passwords[c[b]]=lpdec(passwords[c[b]],AES.hex2bin(SHA256(c[b]))));c.sort(function(a,b){return a.toLowerCase()<b.toLowerCase()?-1:1});create_combo("u",c,!0,document,"","deleteicon",-35,-2);c="";b=document.location.href.indexOf("sesameusername=");-1!=b&&(c=document.location.href.substr(b+15),b=c.indexOf("&"),-1!=b&&(c=c.substring(0,b)),c=decodeURIComponent(c));0<
d.rows.length||""!=c?(c=""!=c?c:d.rows.item(0).username,b="undefined"!=typeof passwords[c]?passwords[c]:"",document.getElementById("u").value=c,document.getElementById("p").focus(),""!=b&&(document.getElementById("p").value=b,-1==rememberpassword&&(document.getElementById("rememberpassword").checked=!0),document.getElementById("login").focus())):document.getElementById("u").focus()},function(a,d){console_log(d)})}),g_ischrome&&(-1!=navigator.userAgent.indexOf("Chrome/4")||-1!=navigator.userAgent.indexOf("Chrome/5"))&&
setTimeout(function(){test_db_failed(1)},5E3)):test_db_failed(0)}}function handle_keydown(a){if(68==(0!=a.keyCode?a.keyCode:a.charCode)&&a.ctrlKey)document.body.innerHTML="<pre>"+getBG().g_console_log+"</pre>",a.cancelBubble=!0,a.preventDefault(),a.stopPropagation()}function test_db_failed(a){L("test_db_failed timeout: "+a);getBG().g_db_transaction_tested=!0;getBG().g_db_transaction_worked||(document.getElementById("u").focus(),create_combo("u",[],!0,document))}
function username_changed(){var a=document.getElementById("u").value;"undefined"!=typeof passwords[a]&&""!=passwords[a]?(document.getElementById("p").value=passwords[a],document.getElementById("rememberpassword").checked=!0):(document.getElementById("p").value="",document.getElementById("rememberpassword").checked=!1)}
function delete_user(){var a=document.getElementById("u").value,e=opendb();createSavedLoginsTable(e);e&&e.transaction(function(d){d.executeSql("DELETE FROM LastPassSavedLogins2 WHERE username=?",[a])},function(){},function(a,c){console_log(c)});delete passwords[a];delete_combo_item("u",a);document.getElementById("u").value="";for(var f in passwords){document.getElementById("u").value=f;break}username_changed()}function retsubmit(a){return 13==a.keyCode?(do_submit(),!1):!0}
function glow(a){a.className+=" glow"}function dim(a){a.className=a.className.replace(/\bglow\b/,"")}
function closePop(){"undefined"!=typeof chrome&&("undefined"!=typeof chrome.runtime||"undefined"!=typeof chrome.extension)&&parent?-1!=document.location.href.indexOf("login.html")?getBG().closecurrenttab("login.html"):parent.window_close():g_ismaxthon?(window.close(),setTimeout(function(){window.external.mxGetRuntime().getActionByName("lppanel").hide()},0)):"undefined"!=typeof getBG().closePop?getBG().closePop():window.close()}function oninitlogin(){}
function onshowlogin(){parent.body&&(parent.body.style.margin="0px");-1==location.search.indexOf("foo")&&(location.href="lp_toolstrip.html?browseraction=1&foo")}function onhidelogin(){parent.body&&(parent.body.style.margin="8px")};
