var KEY_UP=38,KEY_DOWN=40,KEY_ENTER=13,ELEMENT_NODE=1,KEY_ESCAPE=27,KEY_F4=115,KEY_LEFT=37,KEY_RIGHT=39,KEY_HOME=36,KEY_END=35,g_do_complete=!0,g_do_svg=!0;function openCombo(a,b,d,c){c=c?c:document;a=c.getElementById(b);a.disabled||(d=gComboEx=c.getElementById(d),"block"!=d.style.display?showCombo(a,d,null,c):setStyle(d,"display","none",""),gItemNum=-1,gFocusItem=a,("undefined"!=typeof window?window:c.defaultView).setTimeout(function(){doFocus()},0))}
var g_iField=null,g_cb=null,g_combobox_button=null;function showCombo(a,b,d,c){c=c?c:document;g_iField=a;g_cb=b;null!=a&&(b=getComboButtonId(a.id),g_combobox_button=c.getElementById(b),"undefined"!=typeof a.addEventListener?a.addEventListener("move",function(){realShowCombo(c)},!1):a.attachEvent("onmove",function(){realShowCombo(c)}));realShowCombo(c)}function getY(a){for(var b=0;null!=a;)b+=a.offsetTop,a=a.offsetParent;return b}
function getX(a){for(var b=0;null!=a;)b+=a.offsetLeft,a=a.offsetParent;return b}
function realShowCombo(a){null==a&&(a=document);var b=getY(g_iField),d=getX(g_iField),b=b+g_iField.offsetHeight+"px",d=d+"px";g_cb.style.minWidth=g_iField.offsetWidth-14+"px";setStyle(g_cb,"top",b,"");setStyle(g_cb,"left",d,"");setStyle(g_cb,"display","block","");g_combobox_button&&setStyle(g_combobox_button,"display","","");d=LP_getAbsolutePos(a,g_iField);null!=d&&0<d.left&&(a="undefined"!=typeof window&&"undefined"!=typeof window.setTimeout?window:a.defaultView,b=a.innerWidth,null==b&&"undefined"!=
typeof getWindowWidth&&(b=getWindowWidth(a)),null!=b&&0<b&&(g_cb.style.maxWidth=parseInt(b)-parseInt(d.left)-16+"px",parseInt(g_cb.style.maxWidth)<parseInt(g_cb.style.minWidth)&&(g_cb.style.minWidth=g_cb.style.maxWidth)))}var gItemNum=0,gComboEx=null;
function focusCombo(a,b,d){var c="undefined"!=typeof document?document:a.view.document;a=a.keyCode;var e=!0;d=gComboEx=c.getElementById(d);if(a==KEY_DOWN||a==KEY_F4){e=!1;"block"!=d.getAttribute("style.display")&&showCombo(b,d,null,c);b=d.childNode;c=b.length;for(d=0;null!=b[d]&&d<c;){if(b[d].nodeType==ELEMENT_NODE&&"item"==b[d].className&&"none"!=b[d].style.display){gFocusItem=b[d];break}d++}gItemNum=d;d>=c&&(gItemNum=0);setTimeout(function(){doFocus()},0);e=!1}else a!=KEY_ENTER&&a==KEY_ESCAPE&&
(null!=b.val&&0<b.val.length?e=!0:(e=!1,setStyle(gComboEx,"display","none",""),gItemNum=-1));return e}
function focusItem(a,b,d){a=d.val;for(var c=null,e=getItems(b),l=e.length,h=!1,n=0;n<l;n++)if(e[n].hasChildNodes()&&e[n].firstChild.nodeValue==a){h=!0;c=e[n];gItemNum=n;break}h||(c=addItem(b,a,e.length),gItemNum=e.length);null!=c&&(gFocusItem=c,"block"!=gComboEx.getAttribute("style.display")?(a=d.offsetLeft+"px",setStyle(b,"top",d.offsetTop+d.offsetHeight+"px",""),setStyle(b,"left",a,"")):setStyle(b,"display","none",""),setStyle(b,"display","block",""),setTimeout(function(){doFocus()},0))}
function addItem(a,b,d,c){c||(c=document);var e=c.createElement("div"),l="undefined"!=typeof b.label?b.label:b;e.val="undefined"!=typeof b.label?b.value:b;e.label=l;if("undefined"!=typeof b.label&&(e.label=b.label,"undefined"!=typeof b.image)){var h=c.createElement("img");h.src=b.image;h.style.paddingRight="15px";e.appendChild(h);e.img=h.src}b=c.createTextNode(l);e.appendChild(b);e.setAttribute("tabindex","-1");e.setAttribute("class","item");e.setAttribute("data-lpcount",d);"undefined"!=typeof e.addEventListener?
(e.addEventListener("click",function(){gItemNum=this.getAttribute("data-lpcount")}),e.addEventListener("mouseover",function(){gFocusItem=this;doFocus()})):(e.attachEvent("onclick",function(){gItemNum=this.getAttribute("data-lpcount")}),e.attachEvent("onmouseover",function(){gFocusItem=this;doFocus()}));e.setAttribute("role","listitem");e.setAttribute("origText",ofa(l));a.appendChild(e);return e}
function doComboNav(a,b,d,c){var e=a.keyCode,l=!0;null==gComboEx&&(gComboEx=b);if(e==KEY_UP||e==KEY_DOWN){l=!1;a=0;b=getItems(gComboEx);var h=b.length;if(e==KEY_UP)for(a=gItemNum-1;0<=a&&"none"==b[a].style.display;)"none"==b[a].style.display&&a--;else{a=gItemNum+1;for(a==h&&(a=-1);0<=a&&a<h&&"none"==b[a].style.display;)"none"==b[a].style.display&&a++;a==h&&(a=-1)}gItemNum=a;gFocusItem=-1==gItemNum?c.getElementById(d):b[a];setTimeout(function(){doFocus()},0)}else if(e==KEY_ENTER||!a.keyCode&&0<=a.button){if(b=
getItems(gComboEx),e=b[gItemNum],null!=e&&"true"!=e.getAttribute("aria-disabled")){a=e.label;b=e.val;d=c.getElementById(d);d.value=a;d.val=b;"undefined"!=typeof e.img&&(d.style.background="url("+e.img+") no-repeat 2px 5px",d.style.paddingLeft="25px");if(d.onchange)d.onchange();setStyle(gComboEx,"display","none","");gItemNum=0;gFocusItem=d;setTimeout(function(){doFocus()},0)}}else e==KEY_ESCAPE&&(l=!1,setStyle(b,"display","none",""),gItemNum=0,gFocusItem=c.getElementById(d),setTimeout(function(){doFocus()},
0));return l}function getItems(a){if(null===a)return[];var b=[],b=[];a=a.childNodes;for(var d=a.length,c=0;c<d;c++)if(a[c].nodeType==ELEMENT_NODE&&("item"==a[c].getAttribute("class")||"item focus"==a[c].getAttribute("class")))b[b.length]=a[c];return b}
function setStyle(a,b,d,c){var e=!1;try{a.style&&a.style.setProperty&&(a.style.setProperty(b,d,c),e=!0)}catch(l){alert("exception caught setting style: "+l.message)}if(!e)try{a.style[b]=d,e=!0}catch(h){alert("exception caught setting direct style: "+h.message)}return e}var gFocusItem=null,gLastFocusItem=null;
function doFocus(){null!=gFocusItem&&(gFocusItem.focus(),gLastFocusItem&&"item focus"==gLastFocusItem.className&&(gLastFocusItem.className="item"),gFocusItem&&"item"==gFocusItem.className&&(gFocusItem.className="item focus"),gLastFocusItem=gFocusItem,gFocusItem=null)}
function create_combo(a,b,d,c,e,l,h,n,j){var f;c||(c=document);e||(e="");var k=c.getElementById(a),s=getComboId(a);if(!(c.getElementById(s)||null===s)){k.onkeydown=function(a){return focusCombo(a,k,s)};k.onkeyup=function(a){keyupCombo(c,a,k,s);return!1};k.setAttribute("role","textfield");k.setAttribute("aria-haspopup","true");k.setAttribute("autocomplete","off");k.style.marginRight="0px";var g=c.createElement(e+"div");g.setAttribute("role","list");g.setAttribute("style","display: none;");"undefined"!=
typeof g_isie&&g_isie&&(g.style.display="none");g.setAttribute("id",s);g.setAttribute("class","dropStyle");"undefined"!=typeof g_isie&&g_isie&&(g.className="dropStyle");g.onkeydown=function(a){return doComboNav(a,this,this.id.substring(0,this.id.length-6),c)};"undefined"!=typeof g.addEventListener?g.addEventListener("click",function(a){doComboNav(a,this,this.id.substring(0,this.id.length-6),c)}):g.attachEvent("onclick",function(a){doComboNav(a,this,this.id.substring(0,this.id.length-6),c)});g.style.overflowY=
"auto";g.style.overflowX="auto";"undefined"!=typeof g_isie&&g_isie&&(g.style.background="#fff");g.style.paddingLeft="6px";g.style.paddingRight="6px";g.style.position="absolute";g.setAttribute("autofilled","false");j?insertAfter(c.getElementById(j),g):"undefined"!=typeof c.body&&c.body?c.body.appendChild(g):k.parentNode.parentNode.appendChild(g);"undefined"!=typeof k.ownerDocument.defaultView&&"undefined"!=typeof k.ownerDocument.defaultView.addEventListener?(k.ownerDocument.defaultView.addEventListener("click",
function(b){b.target.id!=a&&close_combo(a,c)},!1),k.addEventListener("keydown",function(b){9==b.keyCode&&close_combo(a,c)},!1)):(document.attachEvent("onclick",function(){window.event.srcElement.id!=a&&close_combo(a,c)}),document.attachEvent("onkeydown",function(b){9==b.keyCode&&close_combo(a,c)}));for(j=0;j<b.length;j++)addItem(g,b[j],j,c);b=("undefined"==typeof gLocalBaseUrl?"":gLocalBaseUrl)+"images/pwdrop.png";g_do_svg&&(b=("undefined"==typeof gLocalBaseUrl?"":gLocalBaseUrl)+"images/teardrop.png");
if("undefined"!=typeof g_isie&&g_isie||"undefined"!=typeof g_isfirefox&&g_isfirefox)b="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAfElEQVQ4T2NkoDJgpLJ5DKMGUh6io2GIGobe3t4LGBkZ49FD9v///wu3bt2agC3ECYYhuqH4DANZQNDAgIAAgT9//hwAqtUH4ossLCwOGzZs+IArPRA0EKQRZOjv378nsLKyFuAzjCgXkpoyiXIhKYaOGkhKaGFXS/UwBABG2SEVsoLJ9AAAAABJRU5ErkJggg==";if(d&&"undefined"!=typeof LP_getAbsolutePos){var q=0;d=0;g=c.createElement(e+"div");"undefined"!=typeof c.body&&c.body?l?insertAfter(c.getElementById(l),
g):c.body.appendChild(g):k.parentNode.appendChild(g);var m=getComboButtonId(a);f="";j=3;var t;t="undefined"!=typeof k.ownerDocument.defaultView&&"undefined"!=typeof k.ownerDocument.defaultView.getComputedStyle?k.ownerDocument.defaultView.getComputedStyle(k):k.currentStyle;e=LP_getAbsolutePos(c,k);if(null!=e&&0<e.left&&0<e.top){var r;r=e.left+parseInt(e.width)+4-30;d=q=0;"undefined"!=typeof g_isie&&g_isie&&(d=-4,q=2);f=f+("left:"+(r+d)+"px;")+"position:absolute;";f+="top:"+(parseInt(e.top)+4+q)+"px;";
if("undefined"==typeof g_isfirefox||!g_isfirefox)f+="padding:"+j+"px;"}var p=Math.floor((30-e.height)/2);if(1<=p&&30>e.height&&(d=q=0,f=""+("position:absolute;height:"+(e.height-4)+"px;"),f+="width:"+(e.height-4)+"px;",f+="top:"+(parseInt(e.top)+4+p+4)+"px;",r=e.left+parseInt(e.width)+4-30+p+4,f+="left:"+r+p+"px;",j-=2*p,0>j&&(j=0),"undefined"==typeof g_isfirefox||!g_isfirefox))f+="padding:"+j+"px;";p=Math.round((e.height-30)/2);if(30<e.height&&(d=q=0,"undefined"!=typeof g_isie&&g_isie&&(q=parseInt(t.borderTopWidth),
d=parseInt(t.borderBottomWidth),p-=(q+d)/2,d=-5),f=""+("left:"+(r+d)+"px;"),f+="position:absolute;",f+="top:"+(e.top+p+q)+"px;",j+=2*p,"undefined"==typeof g_isfirefox||!g_isfirefox))f+="padding:"+j+"px;";"undefined"!=typeof g_isie&&g_isie&&(f+="border:0px;");k.style.textOverflow="ellipsis";k.style.whiteSpace="nowrap";l&&(g.style.marginLeft=h?h+"px":"-15px",g.style.display="inline",g.style.verticalAlign="top",g.style.marginTop="6px",f=n?"margin-top:"+n+"px":"margin-top:-18px");l="<img id='"+m+"' src='"+
b+"' valign='middle' style='"+f+"'/>";g.innerHTML="undefined"!=typeof g_isfirefox&&g_isfirefox?xulize(l):l;m=c.getElementById(m);m.onclick=function(a){openCombo(a,this.id.substring(0,this.id.length-7),getComboId(this.id.substring(0,this.id.length-7)),c);null!=a?a.cancelBubble=!0:window.event.cancelBubble=!0};"undefined"!=typeof g_isie&&g_isie||"undefined"!=typeof g_isfirefox&&g_isfirefox||m.setAttribute("onerror","this.removeAttribute('onerror'); this.src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAfElEQVQ4T2NkoDJgpLJ5DKMGUh6io2GIGobe3t4LGBkZ49FD9v///wu3bt2agC3ECYYhuqH4DANZQNDAgIAAgT9//hwAqtUH4ossLCwOGzZs+IArPRA0EKQRZOjv378nsLKyFuAzjCgXkpoyiXIhKYaOGkhKaGFXS/UwBABG2SEVsoLJ9AAAAABJRU5ErkJggg==';")}else!d&&
"undefined"!=typeof LP_getAbsolutePos&&(m=c.createElement(e+"img"),m.id=getComboButtonId(a),null!==m.id&&(m.onclick=function(a){openCombo(a,this.id.substring(0,this.id.length-7),getComboId(this.id.substring(0,this.id.length-7)),c);null!=a?a.cancelBubble=!0:window.event.cancelBubble=!0}),"undefined"!=typeof g_isie&&g_isie||"undefined"!=typeof g_isfirefox&&g_isfirefox||m.setAttribute("onerror","this.removeAttribute('onerror'); this.src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAfElEQVQ4T2NkoDJgpLJ5DKMGUh6io2GIGobe3t4LGBkZ49FD9v///wu3bt2agC3ECYYhuqH4DANZQNDAgIAAgT9//hwAqtUH4ossLCwOGzZs+IArPRA0EKQRZOjv378nsLKyFuAzjCgXkpoyiXIhKYaOGkhKaGFXS/UwBABG2SEVsoLJ9AAAAABJRU5ErkJggg==';"),
m.setAttribute("src",b),m.setAttribute("valign","middle"),"undefined"!=typeof g_isopera&&g_isopera&&m.setAttribute("style","position: relative; top: 7px;"),"undefined"!=typeof c.body&&c.body?c.body.appendChild(m):c.getElementById("main").appendChild(m),e=LP_getAbsolutePos(c,k),null!=e&&(0<e.left&&0<e.top)&&(r=e.left+e.width+2,m.style.left=r+"px",m.style.position="absolute",m.style.top=e.top+"px"),p=Math.floor((30-e.height)/2),1<=p&&30>e.height&&(m.style.height=e.height+"px",m.style.width=e.height+
"px",m.style.top=e.top+p+"px"),p=Math.round((e.height-30)/2),30<e.height&&(m.style.top=e.top+p+"px"));m.className+="teardrop"}}function delete_combo_item(a,b){var d=getComboId(a);if(d=document.getElementById(d))for(var c=getItems(d),e=0;e<c.length;e++)if(c[e].innerHTML==b){for(c.splice(e,1);d.hasChildNodes();)d.removeChild(d.firstChild);for(e=0;e<c.length;e++)addItem(d,c[e].innerHTML,e);break}}
function close_combo(a,b){b||(b=document);var d=getComboId(a);if(d=b.getElementById(d))"block"==d.style.display&&(setStyle(d,"display","none",""),gItemNum=-1),g_do_complete&&unhighlight_combo_all_items(b,a)}function repopulate_combo(a,b,d){d||(d=document);var c=getComboId(a);if(c=d.getElementById(c)){for(;c.hasChildNodes();)c.removeChild(c.firstChild);for(var e=0;e<b.length;e++)addItem(c,b[e],e,d)}a=getComboButtonId(a);(d=d.getElementById(a))&&setStyle(d,"display","","")}
function destroy_combo(a,b){b||(b=document);if(!(null==a||0>=a.length))try{var d=getComboId(a),c=b.getElementById(d);if(c){for(;c.hasChildNodes();)c.removeChild(c.firstChild);c.parentNode.removeChild(c)}var e=getComboButtonId(a),l=b.getElementById(e);l&&l.parentNode.removeChild(l)}catch(h){console.log("destroy_combo error: "+h.message)}}function highlight_combo_item(){return 0}function unhighlight_combo_item(){return 0}function unhighlight_combo_all_items(){return 0}
function getComboId(a){return null===a||""===a?null:a+"_combo"}function getComboButtonId(a){return null===a||""===a?null:a+"_button"}function hide_combo_item(a){null!==a&&setStyle(a,"display","none","")}function show_combo_item(a){null!==a&&setStyle(a,"display","","")}function show_all_combo_items(a,b){a||(a=document);if(!(null==b||0>=b.length)){var d=getComboId(b);if(d=a.getElementById(d))for(var d=getItems(d),c=0;c<d.length;c++)show_combo_item(d[c])}}
function combo_filter(a,b,d){a||(a=document);if(!(null===b||0>=b.length)){var c=!0,e=0;null===d&&(d="");var l=of(d,a),h=null,n=getComboId(b);if(n=a.getElementById(n)){for(var j=getItems(n),f=0;f<j.length;f++){var k="undefined"!=typeof g_isfirefox&&g_isfirefox?j[f].textContent:j[f].innerText;""===d.trim()||0<=k.trim().toLowerCase().indexOf(l.toLowerCase())?(show_combo_item(j[f]),highlight_combo_item(a,b,j[f],d),c=!1,e++,h=j[f]):(hide_combo_item(j[f]),unhighlight_combo_item(a,b,j[f]))}if(c)close_combo(b,
a);else if(d=n.getAttribute("autofilled"),1===e&&"false"==d){n.setAttribute("autofilled","true");if(c=a.getElementById(b))e=c.value.length,d=h.val.length,c.value=h.val,"selectionStart"in c?(c.selectionStart=e,c.selectionEnd=d):(h=c.createTextRange(),h.moveStart("character",e),h.collapse(),h.moveEnd("character",d),h.select());close_combo(b,a)}}}}
function keyupCombo(a,b,d,c){a||(a=document);c=a.getElementById(c);null!==c&&null!==d&&(b=b.keyCode,b==KEY_DOWN||(b==KEY_F4||b==KEY_UP||b==KEY_ENTER||b==KEY_ESCAPE)||(isComboShowing(c)||(showCombo(d,c,null,a),gItemNum=-1,setTimeout(function(){doFocus()},0)),combo_filter(a,d.id,d.value)))}function isComboShowing(a){return null===a?!1:"block"==a.style.display}function insertAfter(a,b){a.parentNode.insertBefore(b,a.nextSibling)};
