var g_iterpw=null;
function lplogincheck(a,c,b,d){console_log("server.js : lplogincheck fromwebsite="+a+" sessionid="+c);if(!skiplogin()){can_chrome_do_math()||openURL(getchromeurl("mathfail.html"));yubikey_cleardata();googleauth_cleardata();outofband_cleardata();securityquestion_cleardata();sesame_cleardata();grid_cleardata();multifactor_cleardata();loginoffline(!0,"logincheck");var f="method="+encodeURIComponent(get_method())+"&version="+lpversion;c&&(f+="&sessionid="+LP.en(c));b&&(f+="&wxusername="+LP.en(b));d&&
(f+="&wxhash="+LP.en(d));g_lastpoll=(new Date).getTime();c=1==lpGetPref("logoffWhenCloseBrowser",0)&&0==lpGetPref("logoffWhenCloseBrowserVal",0)?"1":"0";f+="&sessonly="+en(c);getuuid(function(b){f+="&uuid="+en(b);sesame_setdata("logincheckpostdata",f);lpdbg("login","Making login check request");lpMakeRequest(base_url+"login_check.php",f,lpLoginCheckResponse,lpLoginCheckError,a)})}}
function LP_do_login(a,c,b,d,f,e,g,h){console_log("server.js : LP_do_login");if(!skiplogin())if(g){lppassusernamehash&&!lploggedin&&lpnp_notify("login",{data0:a,data1:c});if(!f){var n=opendb();createSavedLoginsTable(n);if(n&&"undefined"!=typeof b&&null!=b){var m=d?c:"";protect_data(m,!1,a,function(c){n.transaction(function(d){if(b&&check_email(a)){var e=c!=m?1:0;!e&&""!=m&&(c=lpenc(c,AES.hex2bin(SHA256(a))),e=2);console_log("server.js : saving login credentials");d.executeSql("REPLACE INTO LastPassSavedLogins2 (username, password, last_login, protected) VALUES(?, ?, ?, ?)",
[a,c,(new Date).getTime(),e],function(){},function(a,b){console_log(b)})}else d.executeSql("DELETE FROM LastPassSavedLogins2 WHERE username=?",[a],function(){},function(a,b){console_log(b)})})})}"undefined"!=typeof b&&null!=b&&(lpPutGblPref("rememberemail",b?1:0),lpPutGblPref("rememberpassword",d?1:0));"undefined"!=typeof e&&lpPutGblPref("showvault",e?1:0);lpWriteAllPrefs()}yubikey_cleardata();googleauth_cleardata();outofband_cleardata();securityquestion_cleardata();sesame_cleardata();grid_cleardata();
f||multifactor_cleardata();a=fix_username(a);var l=get_key_iterations(a);g_local_key=g?g:make_lp_key_iterations(a,c,l);"string"==typeof c&&c.length&&calculateMasterStrength(a,c);g_local_hash=h?lphash=h:lphash=make_lp_hash_iterations(g_local_key,c,l);g_local_key_hex=AES.bin2hex(g_local_key);g_local_key_hash=SHA256(g_local_key);g_username=lpusername=a;g_username_hash=lpusername_hash=SHA256(g_username);lploggedinoffline||loginoffline(!0,"pluginlogin");var k="xml=2&username="+en(a)+"&method="+encodeURIComponent(get_method())+
"&hash="+en(g_local_hash)+"&version="+lpversion,k=k+("&encrypted_username="+en(lpenc(g_username,null,!0)));getuuid(function(b){k+="&uuid="+en(b);k+="&lang="+en(lpGetPref("language",navigator.language));b=get_key_iterations(a);k+="&iterations="+en(b);""!=b&&1<parseInt(b)&&(b=checkNeedsPBKDF2v2(a,c),k+=b,""!=b&&("undefined"!=typeof g_oldpbkdf2&&1==g_oldpbkdf2)&&(k+="&fallback=1"));b=1==lpGetPref("logoffWhenCloseBrowser",0)&&0==lpGetPref("logoffWhenCloseBrowserVal",0)?"1":"0";k+="&sessonly="+en(b);sesame_cleardata();
sesame_setdata("postdata",k);sesame_setdata("from","login");yubikey_cleardata();yubikey_setdata("postdata",k);yubikey_setdata("from","login");g_iterpw=c;googleauth_cleardata();googleauth_setdata("postdata",k);googleauth_setdata("from","login");outofband_cleardata();outofband_setdata("postdata",k);outofband_setdata("from","login");securityquestion_cleardata();securityquestion_setdata("postdata",k);securityquestion_setdata("from","login");grid_cleardata();grid_setdata("postdata",k);grid_setdata("from",
"login");f||multifactor_cleardata();multifactor_setdata("postdata",k);multifactor_setdata("from","login");k+="&otp=";k+="&sesameotp=";k+="&multifactorresponse=";GetOTPHash(k)})}else make_lp_key_iterations(a,c,get_key_iterations(a),function(g){LP_do_login(a,c,b,d,f,e,g,h)})}
function loginoffline(a,c){console_log("server.js : loginoffline from="+c+" offline_before_online="+a);if(!skiplogin())if(null==g_local_key||null==g_username||null==g_username_hash){if("frompipes"!=c){var b=opendb();createSavedLoginsTable(b);b&&b.transaction(function(d){console_log("server.js : getting login credentials");d.executeSql("SELECT * FROM LastPassSavedLogins2 order by last_login desc",[],function(d,e){var g="",h="",n=function(d){if((!LPISLOC||!LPISUPEK)&&0<g.length&&0<d.length){g_username=
lpusername=g.toLowerCase().replace(/\s*/g,"");g_username_hash=lpusername_hash=SHA256(g);var e=get_key_iterations(g_username);make_lp_key_iterations(g_username,d,e,function(b){g_local_key=b;g_local_hash=lphash=make_lp_hash_iterations(g_local_key,d,e);g_local_key_hex=AES.bin2hex(g_local_key);g_local_key_hash=SHA256(g_local_key);loginoffline1(a,c)})}else LPISLOC&&b.transaction(function(a){a.executeSql("SELECT prefvalue FROM LastPassPreferences where username_hash=? and prefname=?",["","openloginstart"],
function(a,b){if(LPISUPEK||1==b.rows.length&&b.rows.item(0).prefvalue)if(1==lpGetPref("openloginstart",LPISUPEK?1:0))g_reprompt_error_callback=g_reprompt_callback=null,open_login()},function(a,b){console_log(b)})})};if(0<e.rows.length){g=e.rows.item(0).username;h=e.rows.item(0).password;if(1==e.rows.item(0)["protected"]){unprotect_data(h,!1,n);return}if(2==e.rows.item(0)["protected"]){n(lpdec(h,AES.hex2bin(SHA256(g))));return}n(h)}lpdbg("login","Trying to log in offline1: skipping because we dont have the user's key")},
function(){lpdbg("login","Trying to log in offline2: skipping because we dont have the user's key")})})}}else loginoffline1(a,c)}function read_key_from_file(a){have_binary_function("read_file")?call_binary_function("read_file",db_prepend(g_username_hash+"_lpall.slps"),function(c){"string"!=typeof c?a(""):unprotect_data(c,!0,a)}):a("")}
function read_accts_from_file(a){have_binary_function("read_file")?call_binary_function("read_file",db_prepend(g_username_hash+"_lps.act.sxml"),function(c){"string"!=typeof c?a(""):unprotect_data(c,!0,function(b){b=checkIterationsInDataFile(b);"iterationserror"==b?(lpdbg("login","Key iterations mismatch"),a("")):(b=lpdec(b),a(b))})}):a("")}
function loginoffline1(a,c,b){console_log("server.js : loginoffline1 offline_before_online="+a+" from="+c);if(a){if(!g_loggedinoffline){console_log("server.js : DB:opening database");var d=opendb();console_log("server.js : DB:opened database db="+d);createDataTable(d);d?(console_log("server.js : DB:created database"),d.transaction(function(d){var e=function(d,e){console_log("server.js : DB:inside transaction A");if(2!=e.rows.length)console_log("server.js : DB:inside transaction B"),LPISLOC&&(!LPISUPEK||
b||""==g_username||AES.hex2bin(SHA256(g_username+""))==g_local_key?lpshowError("LoginError",!1,!0):(g_pwdeckey=g_local_key,lpWriteKeyFile(),g_local_accts_version=0,LPISUPEK&&(g_prompts.login_site_prompt=!0,g_prompts.edit_site_prompt=!0,g_prompts.edit_sn_prompt=!0,g_prompts.view_pw_prompt=!0,g_prompts.view_ff_prompt=!0,g_prompts.switch_identity_prompt=!0,g_prompts.switch_f_prompt=!0,g_prompts.multifactor_reprompt=!0),rewritelocalfile(),loginoffline1(a,c,!0))),console_log("server.js : DB:inside transaction C"),
lpdbg("login","Trying to log in offline : offline before online failed : could not read keyfile or accts");else{console_log("server.js : DB:inside transaction D");var f="key"==e.rows.item(0).type?0:1,g=e.rows.item(f).data,f=!1,g=g.split("\n");2==g.length&&"lastpass rocks"==lpdec(g[1],g_local_key)&&(console_log("server.js : DB:inside transaction E"),f=!0);f?(console_log("server.js : DB:inside transaction G"),f="accts"==e.rows.item(0).type?0:1,g=e.rows.item(f).data,g=g.substring(0,220),g=checkIterationsInDataFile(g),
"iterationserror"==g?lpdbg("login","Key iterations mismatch, bailing on loginoffline"):0<=g.indexOf("type=sesameoffline\ndata=")||0<=g.indexOf("type=yubikeyoffline\ndata=")||0<=g.indexOf("type=trueapioffline\ndata=")||0<=g.indexOf("type=omnikeyoffline\ndata=")?(console_log("server.js : DB:inside transaction H"),lpdbg("login","Data is encoded with multifactor key, bailing on loginoffline")):(console_log("server.js : DB:inside transaction I"),offlineloginsuccessful(c,!0),lpdbg("login","Trying to log in offline : offline before online successful"))):
(console_log("server.js : DB:inside transaction F"),LPISLOC&&lpshowError("LoginError",!1,!0),lpdbg("login","Trying to log in offline: skipping because we have an incorrect user's key"))}},g=function(){lpdbg("login","Trying to log in offline3: skipping because we dont have the user's key")};LPISLOC?read_key_from_file(function(a){read_accts_from_file(function(b){""!=a||""!=b?e(d,{rows:{length:2,item:function(c){return 0==c?{type:"key",data:a}:{type:"accts",data:b}}}}):e(d,{rows:{length:0}})})}):d.executeSql("SELECT * FROM LastPassData WHERE username_hash=? AND (type=? OR type=?)",
[db_prepend(g_username_hash),"key","accts"],e,g)})):console_log("server.js : DB:failed to create database db="+d)}}else g_loggedinoffline||(d=opendb(),createDataTable(d),d&&d.transaction(function(a){var b=function(a,b){if(2!=b.rows.length)lpdbg("login","Trying to log in offline : offline before online failed : could not read keyfile or accts");else{var d="key"==b.rows.item(0).type?0:1,e=b.rows.item(d).data,d=!1,e=e.split("\n");2==e.length&&"lastpass rocks"==lpdec(e[1],g_local_key)&&(d=!0);d?(d="accts"==
b.rows.item(0).type?0:1,e=b.rows.item(d).data,e=e.substring(0,220),e=checkIterationsInDataFile(e),"iterationserror"==e?lpdbg("login","Trying to log in offline: skipping because we have a key iterations mismatch"):0<=e.indexOf("type=sesameoffline\ndata=")?(lpdbg("sesame","Logging in offline and existing file is protected by sesameoffline => asking user for offline password"),sesame_setdata("offline",1),sesame_getotp(null)):0<=e.indexOf("type=trueapioffline\ndata=")||0<=e.indexOf("type=omnikeyoffline\ndata=")?
(lpdbg("multifactor","Logging in offline and existing file is protected by trueapioffline => asking user for offline password"),d=0<=e.indexOf("type=trueapioffline\ndata=")?"trueapi":"omnikey",multifactor_setdata("offline",1),multifactor_setdata("type",d),multifactor_getresponse(g_username)):0<=e.indexOf("type=yubikeyoffline\ndata=")?(yubikey_setdata("offline",1),yubikey_getotp(null)):(offlineloginsuccessful(c,!1),lpdbg("login","Trying to log in offline : offline after online successful"))):lpdbg("login",
"Trying to log in offline: skipping because we have an incorrect user's key")}};LPISLOC?read_key_from_file(function(c){read_accts_from_file(function(d){""!=c||""!=d?b(a,{rows:{length:2,item:function(a){return 0==a?{type:"key",data:c}:{type:"accts",data:d}}}}):b(a,{rows:{length:0}})})}):a.executeSql("SELECT * FROM LastPassData WHERE username_hash=? AND (type=? OR type=?)",[db_prepend(g_username_hash),"key","accts"],b)}))}
function offlineloginsuccessful(a,c){console_log("server.js : offlineloginsuccessful beforeonlineattempt="+c+" from="+a);if(LPISLOC&&("pluginlogin"==a&&g_manual_login)&&(1==lpGetPref("showvault",g_showvaultdefault)||g_showvaultalways))console_log("server.js : offlineloginsuccessful openvault offline version!"),openvault(1);console_log("server.js : offlineloginsuccessful!");g_loggedinonline||(g_loggedinoffline=!0);lploggedin=!0;lpReadAllPrefs();loggedIn("pluginlogin"==a);readrsaprivatekeyhexfromdb();
"offline"!=a&&(console_log("server.js : offlineloginsuccessful : from "+a+" so calling get_accts_local!"),get_accts_local(!0));g_notifytimerid&&(clearTimeout(g_notifytimerid),g_notifytimerid=null);g_notifytimerid=setTimeout(function(){notifyoffline(a)},c?3E4:0);g_retryonlinetimerid&&(clearTimeout(g_retryonlinetimerid),g_retryonlinetimerid=null);g_retryonlinetimerid=setTimeout(function(){retryonlinelogin(3E4)},3E4)}
function notifyoffline(a){console_log("server.js : notifyoffline from="+a);lploggedin&&g_loggedinoffline&&(lpdbg("login","Trying to log in offline : notify user that they are logged in offline"),LPISLOC||lpshowError("LoggedInOffline",!1,!1,!1,null,!0))}
function retryonlinelogin(a){console_log("server.js : retryonlinelogin delayms="+a);if(lploggedin&&g_loggedinoffline){lpdbg("login","We're still logged in offline => retrying to login online.  retryinterval="+a/6E4+" minutes");lplogincheck("retryonline");var c=2*a;12E5<c&&(c=12E5);setTimeout(function(){retryonlinelogin(c)},c)}}function lpTurnOffIcon(){lploggedin=!1;drawIconAtRotation(0)}
function lpLoginCheckResponse(a,c,b){console_log("server.js : lpLoginCheckResponse fromwebsite="+b);try{if(a&&4==a.readyState&&"function"==typeof c&&(200!=a.status||null==a.responseXML||null==a.responseXML.documentElement))c();else{if(4==a.readyState&&200==a.status&&null!=a.responseXML&&null!=a.responseXML.documentElement){var d=a.responseXML.documentElement.getElementsByTagName("ok");if(0<d.length){var f=d[0].getAttribute("lpusername");g_username=lpusername=f;g_username_hash=SHA256(g_username);if("retryonline"!=
b&&!0!=b){lpReadAllPrefs(function(){lpLoginCheckResponseStep2(a,f,b)});return}}}lpLoginResponse_win(a,b,!0)}}catch(e){L("logincheckresponse: "+e)}}
function lpLoginCheckResponseStep2(a,c,b){console_log("server.js : lpLoginCheckResponseStep2 fromwebsite="+b);try{var d=a.responseXML.documentElement.getElementsByTagName("ok");lpdbg("login","lpLoginCheckResponseStep2");var f=null!=d[0].getAttribute("sesamepassword")&&""!=d[0].getAttribute("sesamepassword")?!0:!1,e=null!=d[0].getAttribute("yubikeyhash")&&""!=d[0].getAttribute("yubikeyhash")?!0:!1,g=null!=d[0].getAttribute("googleauthenabled")&&"1"==d[0].getAttribute("googleauthenabled")?!0:!1,h=null!=
d[0].getAttribute("gridenabled")&&""!=d[0].getAttribute("gridenabled")?!0:!1,n=null!=d[0].getAttribute("multifactorenabled")&&""!=d[0].getAttribute("multifactorenabled")?!0:!1,m=null!=d[0].getAttribute("sesameotpok")&&""!=d[0].getAttribute("sesameotpok")?!0:!1,l=null!=d[0].getAttribute("yubikeyotpok")&&""!=d[0].getAttribute("yubikeyotpok")?!0:!1,k=null!=d[0].getAttribute("googleauthotpok")&&""!=d[0].getAttribute("googleauthotpok")?!0:!1,p=null!=d[0].getAttribute("gridresponseok")&&""!=d[0].getAttribute("gridresponseok")?
!0:!1,r=null!=d[0].getAttribute("multifactorresponseok")&&""!=d[0].getAttribute("multifactorresponseok")?!0:!1,v=null!=d[0].getAttribute("disableoffline")&&1==d[0].getAttribute("disableoffline")?!0:!1;console_log("server.js : ***** disableoffline="+v);if(!("websitelogin"==b||"webrootwebsitelogin"==b||"websiterefresh"==b||"websiterefreshrsa"==b||"2ndfactorok"==b||"frompipes"==b)&&(null==g_local_key||""==g_local_key)&&1==lpGetPref("logoffWhenCloseBrowser",0)){var w=lpGetPref("lastpollcheck",0),t=lpGetPref("logoffWhenCloseBrowserVal",
0),s=1E3*lp_get_gmt_timestamp()-w;console_log("server.js : "+w+" "+t+" "+s);if(s>=6E4*t){loggedOut(!1,"logoffWhenCloseBrowser lastpollcheck="+w+" logoffWhenCloseBrowserVal="+t+" timesincelastpollcheck="+s);if(1==lpGetPref("openloginstart",LPISUPEK?1:0))g_reprompt_error_callback=g_reprompt_callback=null,open_login();return}}if("httptest"==b){if(v&&!h&&!g){console_log("server.js : Logging out since disableoffline=1 gridenabled="+h+" gridresponseok="+p);loggedOut(!1,"disableoffline");if(1==lpGetPref("openloginstart",
LPISUPEK?1:0))g_reprompt_error_callback=g_reprompt_callback=null,open_login();return}if(f)if(m)b="2ndfactorok",lpdbg("login","LoginCheck : sesame reprompt-rerequest succeeded!");else{lpdbg("login","LoginCheck : Asking for sesame OTP and reissuing request to login_check.php");lpdbg("sesame","LOGIN CHECK RESPONSE: sesameenabled => Asking user for OTP and then reissuing the login_check request");sesame_setdata("fromwebsite",b);lpCheckForKey(function(){sesame_getotp(c)});return}if(e)if(l)b="2ndfactorok",
lpdbg("login","LoginCheck : yubikey reprompt-rerequest succeeded!");else{lpdbg("login","LoginCheck : Asking for yubikey OTP and reissuing request to login_check.php");lpdbg("yubikey","LOGIN CHECK RESPONSE: yubikeyenabled => Asking user for OTP and then reissuing the login_check request");yubikey_setdata("fromwebsite",b);lpCheckForKey(function(){yubikey_getotp(c)});return}if(g)if(k)b="2ndfactorok",lpdbg("login","LoginCheck : googleauth reprompt-rerequest succeeded!");else{lpdbg("login","LoginCheck : Asking for googleauth OTP and reissuing request to login_check.php");
lpdbg("googleauth","LOGIN CHECK RESPONSE: googleauthenabled => Asking user for OTP and then reissuing the login_check request");googleauth_setdata("fromwebsite",b);lpCheckForKey(function(){googleauth_getotp(c)});return}if(h)if(p)b="2ndfactorok",lpdbg("login","LoginCheck : grid reprompt-rerequest succeeded!");else{lpdbg("login","LoginCheck : Asking for grid response and reissuing request to login_check.php");lpdbg("grid","LOGIN CHECK RESPONSE: gridenabled => Asking user for coordinates and then reissuing the login_check request");
grid_setdata("fromwebsite",b);grid_setdata("wxsessid",d[0].getAttribute("wxsessid"));grid_getvalues(c,d[0].getAttribute("challenge"));return}if(n)if(r)b="2ndfactorok",lpdbg("login","LoginCheck : multifactor reprompt-rerequest succeeded!"),"omnikey"==multifactor_getdata("type")&&multifactor_setdata("password_offline",d[0].getAttribute("multifactorofflinepassword"));else{lpdbg("login","LoginCheck : Asking for multifactor response and reissuing request to login_check.php");lpdbg("multifactor","LOGIN CHECK RESPONSE: multifactorenabled => Asking user for coordinates and then reissuing the login_check request");
multifactor_setdata("fromwebsite",b);multifactor_setdata("wxsessid",d[0].getAttribute("wxsessid"));multifactor_setdata("type",d[0].getAttribute("type"));multifactor_getresponse(c,d[0].getAttribute("challenge"));return}}lpLoginResponse_win(a,b,!0)}catch(q){console_log(q.message)}}
function lpLoginResponse(a,c,b){console_log("server.js : lpLoginResponse fromwebsite="+b);try{console_log("server.js : Got login response"),a&&4==a.readyState&&"function"==typeof c&&(200!=a.status||null==a.responseXML||null==a.responseXML.documentElement)?c():(console_log("server.js : Processing login response"),lpLoginResponse_win(a,b,!1))}catch(d){L("loginresponse: "+d)}}
function lp_login_from_saved(){console_log("server.js : lp_login_from_saved");try{var a=opendb();createSavedLoginsTable(a);a&&a.transaction(function(b){b.executeSql("SELECT * FROM LastPassSavedLogins2 order by last_login desc",[],function(b,c){if(0<c.rows.length){var e=c.rows.item(0).username,g=c.rows.item(0).password;if(""!=g){var h=function(a){if((!LPISLOC||!LPISUPEK)&&""!=a)console_log("server.js : Logging in from saved"),LP_do_login(e,a,!0,!0)};1==c.rows.item(0)["protected"]?unprotect_data(g,
!1,h):2==c.rows.item(0)["protected"]&&h(lpdec(g,AES.hex2bin(SHA256(c.rows.item(0).username))));return}}a.transaction(function(a){a.executeSql("SELECT prefvalue FROM LastPassPreferences where username_hash=? and prefname=?",["","openloginstart"],function(a,b){if(LPISUPEK||1==b.rows.length&&b.rows.item(0).prefvalue)if(1==lpGetPref("openloginstart",LPISUPEK?1:0))g_reprompt_error_callback=g_reprompt_callback=null,open_login()},function(a,b){console_log(b)})})},function(a,b){console_log(b)})})}catch(c){console_log(c.message)}}
function lpLoginCommon(a){console_log("server.js : lpLoginCommon bIsLoginCheck="+a);g_loggedinonline=!0;g_loggedinoffline=!1;g_notifytimerid&&(clearTimeout(g_notifytimerid),g_notifytimerid=null);g_retryonlinetimerid&&(clearTimeout(g_retryonlinetimerid),g_retryonlinetimerid=null)}var lploginerrorhandlercalled=0;
function lpLoginError(){console_log("server.js : lpLoginError");console_log("server.js : Got Login Error");var a=(new Date).getTime();1E3>a-lploginerrorhandlercalled||(lploginerrorhandlercalled=a,lpdbg("login","Login via login.php failed => try logging in offline using saved credentials -- if not already logged in offline --"),loginoffline(!1,"ErrorHandler"))}
function lpLoginCheckError(){console_log("server.js : lpLoginCheckError");lpdbg("login","Got lpLoginCheckError");g_loggedinoffline||(lpshowError("ErrorLoginMsg"),loggedOut(!1,"lpLoginCheckError"),lp_login_from_saved())}
function lpLoginResponse_win(a,c,b){console_log("server.js : lpLoginResponse_win fromwebsite="+c+" bIsLoginCheck="+b);if(a)if(4==a.readyState&&200==a.status&&null!=a.responseXML&&null!=a.responseXML.documentElement){var d=a.responseXML.documentElement,f=d.getElementsByTagName("ok"),e=!1;lpdbg("login","lpLoginResponse_win");if(0<f.length)if(lpdbg("login","got login ok"),g_username=f[0].getAttribute("lpusername"),"1"==f[0].getAttribute("pwresetreqd"))a=g_username,b?openurlifnotopen(base_url+"passwordreset.php?u="+
en(a)):openURL(base_url+"passwordreset.php?u="+en(a));else{if(f[0].getAttribute("iterations")){e=parseInt(f[0].getAttribute("iterations"));if(!checkIterationsReductionOk(e))return;try{localStorage.setItem(SHA256(g_username)+"_key_iter",e)}catch(g){L("Failed to setItem("+SHA256(g_username)+"_key_iter) e: "+g)}}g_iterpw="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";g_pwdeckey=AES.hex2bin(SHA256(f[0].getAttribute("pwdeckey")));g_username_hash=SHA256(g_username);
g_uid=lpuid=f[0].getAttribute("uid");g_logoff_other_ses="1"==f[0].getAttribute("logoff_other_ses")?!0:!1;g_generatedpw="1"==f[0].getAttribute("generatedpw")?!0:!1;countryfromip=f[0].getAttribute("country");g_lastpollcheck=g_lastpoll=(new Date).getTime();g_token=lptoken=f[0].getAttribute("token");if((e=f[0].getAttribute("pollinterval"))&&-1!=e&&!isNaN(parseInt(e))&&isFinite(e))lpPutUserPref("pollServerVal",e),lpWriteAllPrefs(),g_flags.pollIntervalSetByPolicy=1;getsinglefactortype(function(a){"1"==
f[0].getAttribute("multifactor_singlefactor")?""==a&&("trueapi"==multifactor_getdata("type")?have_binary_function("trueapi_default_login_exists")&&call_binary_function("trueapi_default_login_exists",g_username,function(a){a&&setsinglefactortype(multifactor_getdata("type"))}):"vtapi"==f[0].getAttribute("singlefactortype")?have_binary_function("lpvt_has_data")&&call_binary_function("lpvt_has_data",function(a){a&&setsinglefactortype(f[0].getAttribute("singlefactortype"))}):"validity"==f[0].getAttribute("singlefactortype")?
have_binary_function("validity_has_data")&&call_binary_function("validity_has_data",function(a){a&&setsinglefactortype(f[0].getAttribute("singlefactortype"))}):"winbio"==f[0].getAttribute("singlefactortype")&&have_binary_function("winbio_has_data")&&call_binary_function("winbio_has_data",function(a){a&&setsinglefactortype(f[0].getAttribute("singlefactortype"))})):""!=a&&disable_single_factor()});sesame_setdata("password_offline",f[0].getAttribute("sesamepassword"));yubikey_setdata("password_offline",
f[0].getAttribute("yubikeyhash"));if((e=f[0].getAttribute("note_title"))&&e.length){var d=f[0].getAttribute("note_text"),h=f[0].hasAttribute("note_url")?f[0].getAttribute("note_url"):null;handlenotifications(e,d,h)}lpLoginResponse_win1_5(a,c,b);lpLoginCommon(b);if(lpdisableoffline=1==f[0].getAttribute("disableoffline")?1:0)lpdbg("disableoffline","server.js : enabled => clearing sensitive files"),clearCache(!0,!1,!1,!0);if(g_manual_login&&(1==lpGetPref("showvault",g_showvaultdefault)||g_showvaultalways))console_log("openvault from login okay"),
openvault(1)}else{console_log(a.responseText);b=d.getElementsByTagName("error");if(0<b.length){lpdbg("login","got login error");if(b[0].getAttribute("iterations")){e=parseInt(b[0].getAttribute("iterations"));if(checkIterationsReductionOk(e)){try{localStorage.setItem(SHA256(g_username)+"_key_iter",e)}catch(n){console.error("Failed to setItem("+SHA256(g_username)+"_key_iter) e: "+n),DEFAULT_KEY_ITERATIONS=e}LP_do_login(g_username,g_iterpw)}return}if(b[0].getAttribute("pbkdf2fallback")&&("undefined"==
typeof g_oldpbkdf2||1!=g_oldpbkdf2)){g_oldpbkdf2=1;yubikey_getdata("p");LP_do_login(g_username,g_iterpw);return}"undefined"!=typeof g_oldpbkdf2&&(g_oldpbkdf2=0);if(b[0].getAttribute("server")){a=b[0].getAttribute("server");if("lastpass.com"==a||"lastpass.eu"==a)base_url="https://"+a+"/",lpPutGblPref("server",a),LP_do_login(g_username,g_iterpw);return}b[0].getAttribute("openurl")&&(e=b[0].getAttribute("openurl"),openURL(e));if(b[0].hasAttribute("invalidsession")){openURL(base_url+"invalidsession.php");
lpshowError(0<b.length&&b[0].getAttribute("message")?b[0].getAttribute("message"):"LoginError",!1,!0);clearCache(!0,!1,!1);loggedOut(!1,"invalidsession");return}e=1==parseInt(b[0].getAttribute("silent"));if(0<a.responseText.indexOf("sesameotprequired")){lpdbg("sesame","LOGIN RESPONSE: sesameenabled => Asking user for OTP and then reissuing the login request");clearCache(!0,!1,!1);sesame_setdata("fromwebsite",c);sesame_getotp(g_username);return}if(0<a.responseText.indexOf("sesameotpfailed")){lpshowError(0<
b.length&&b[0].getAttribute("message")?b[0].getAttribute("message"):"LoginError",!1,!0);clearCache(!0,!1,!1);loggedOut(!1,"sesameotpfailed");return}if(0<a.responseText.indexOf("otprequired")){lpdbg("yubikey","LOGIN RESPONSE: yubikeyenabled => Asking user for OTP and then reissuing the login request");clearCache(!0,!1,!1);yubikey_setdata("fromwebsite",c);yubikey_getotp(g_username);return}if(0<a.responseText.indexOf("otpfailed")){lpshowError(0<b.length&&b[0].getAttribute("message")?b[0].getAttribute("message"):
"LoginError",!1,!0);clearCache(!0,!1,!1);loggedOut(!1,"otpfailed");return}d=!1;if(0<a.responseText.indexOf("googleauthfailed"))if(d=googleauth_getdata("fail_count"),null==d&&(d=0),d++,googleauth_setdata("fail_count",d),5>d)d=!0;else{googleauth_setdata("fail_count",0);lpshowError(0<b.length&&b[0].getAttribute("message")?b[0].getAttribute("message"):"LoginError",!1,!0);clearCache(!0,!1,!1);loggedOut(!1,"otpfailed");return}h=!1;if(0<a.responseText.indexOf("securityquestionfailed"))if(h=securityquestion_getdata("fail_count"),
null==h&&(h=0),h++,securityquestion_setdata("fail_count",h),5>h)0<b.length&&b[0].getAttribute("message")&&alert(b[0].getAttribute("message")),h=!0;else{securityquestion_setdata("fail_count",0);lpshowError(0<b.length&&b[0].getAttribute("message")?b[0].getAttribute("message"):"LoginError",!1,!0);clearCache(!0,!1,!1);loggedOut(!1,"otpfailed");return}if(0<a.responseText.indexOf("googleauthrequired")||d){lpdbg("googleauth","LOGIN RESPONSE: googleauthenabled => Asking user for OTP and then reissuing the login request");
clearCache(!0,!1,!1);googleauth_setdata("fromwebsite",c);googleauth_getotp(g_username);return}if(0<a.responseText.indexOf("outofbandrequired")){lpdbg("outofband","LOGIN RESPONSE: outofbandenabled => Asking user for OTP and then reissuing the login request");clearCache(!0,!1,!1);outofband_setdata("fromwebsite",c);outofband_getotp(g_username,b[0]);return}if(0<a.responseText.indexOf("securityquestionrequired")||h){lpdbg("securityquestion","LOGIN RESPONSE: securityquestionenabled => Asking user for answer and then reissuing the login request");
clearCache(!0,!1,!1);securityquestion_setdata("fromwebsite",c);securityquestion_getotp(g_username,b[0]);return}if(0<a.responseText.indexOf("gridresponserequired")){lpdbg("grid","LOGIN RESPONSE: gridenabled => Asking user for grid response and then reissuing the login request");clearCache(!0,!1,!1);grid_setdata("fromwebsite",c);grid_setdata("wxsessid",b[0].getAttribute("wxsessid"));grid_getvalues(g_username,b[0].getAttribute("challenge"));return}if(0<a.responseText.indexOf("gridresponsefailed")){lpshowError(0<
b.length&&b[0].getAttribute("message")?b[0].getAttribute("message"):"LoginError",!1,!0);clearCache(!0,!1,!1);loggedOut(!1,"gridresponsefailed");return}if(0<a.responseText.indexOf("multifactorresponserequired")){lpdbg("multifactor","LOGIN RESPONSE: multifactorenabled => Asking user for multifactor response and then reissuing the login request");clearCache(!0,!1,!1);multifactor_setdata("fromwebsite",c);multifactor_setdata("wxsessid",b[0].getAttribute("wxsessid"));multifactor_setdata("type",b[0].getAttribute("type"));
multifactor_getresponse(g_username,b[0].getAttribute("challenge"));return}if(0<a.responseText.indexOf("multifactorresponsefailed")){lpshowError(0<b.length&&b[0].getAttribute("message")?b[0].getAttribute("message"):"LoginError",!1,!0,!1,get_multifactor_disable_url(g_username,multifactor_getdata("type")));clearCache(!0,!1,!1);loggedOut(!1,"multifactorresponsefailed");return}}loggedOut(e,"lpLoginResponse_win A");e?lp_login_from_saved():0<a.responseText.indexOf("blacklist")?(clearCache(!0,!1,!1),lpshowError(0<
b.length&&b[0].getAttribute("message")?b[0].getAttribute("message"):"Blacklist",!1,!0,!1,null,!1,b[0].getAttribute("custombutton"),b[0].getAttribute("customaction"))):(a=0<b.length&&b[0].getAttribute("cause")&&"unknownemail"==b[0].getAttribute("cause"),lpshowError(0<b.length&&b[0].getAttribute("message")?b[0].getAttribute("message"):"LoginError",!1,!0,a,null,!1,b[0].getAttribute("custombutton"),b[0].getAttribute("customaction")))}}else loggedOut(!1,"lpLoginResponse_win B"),lpshowError("ErrorLoginMsg")}
function disable_single_factor(){getsinglefactortype(function(a){"trueapi"==a&&have_binary_function("trueapi_delete_default_login")&&call_binary_function("trueapi_delete_default_login");setsinglefactortype("")})}
function lpLoginResponse_win1_5(a,c,b){console_log("server.js : lpLoginResponse_win1_5 fromwebsite="+c+" bIsLoginCheck="+b);a.responseXML.documentElement.getElementsByTagName("ok");null==g_local_key||""==g_local_key?!("websitelogin"==c||"webrootwebsitelogin"==c||"websiterefresh"==c||"websiterefreshrsa"==c||"2ndfactorok"==c||"frompipes"==c)&&1==lpGetPref("logoffWhenCloseBrowser",0)?lpReadAllPrefs(function(){lpLoginResponse_win1_75(a,c,b)}):lpReadKeyFile(a,c,!1,b):(lpWriteKeyFile(),lpReadAllPrefs(function(){lpLoginResponse_win2(a,
c,b)}))}function lpLoginResponse_win1_75(a,c,b){console_log("server.js : lpLoginResponse_win1_75 fromwebsite="+c+" bIsLoginCheck="+b);var d=lpGetPref("lastpollcheck",0),f=lpGetPref("logoffWhenCloseBrowserVal",0),e=1E3*lp_get_gmt_timestamp()-d;e>=6E4*f?loggedOut(!1,"lpLoginResponse_win1_75 lastpollcheck="+d+" logoffWhenCloseBrowserVal="+f+" timesincelastpollcheck="+e):lpReadKeyFile(a,c,!1,b)}
function lpLoginResponse_win2(a,c,b){console_log("server.js : lpLoginResponse_win2 fromwebsite="+c+" bIsLoginCheck="+b);var d=a.responseXML.documentElement,d=d.getElementsByTagName("ok");closeallnotifications(!0,!0);lp_phpsessid=d[0].getAttribute("sessionid");loggedIn();g_server_accts_version=parseInt(d[0].getAttribute("accts_version"));lp_server_attach_version=parseInt(d[0].getAttribute("attachversion"));g_server_accts_version!=g_local_accts_version&&(g_local_accts_version=-1);g_loglogins=parseInt(d[0].getAttribute("loglogins"));
g_isadmin=1==parseInt(d[0].getAttribute("isadmin"));g_iscompanyadmin=1==parseInt(d[0].getAttribute("companyadmin"));g_showcredmon=1==parseInt(d[0].getAttribute("showcredmon"));iconsversion=parseInt(d[0].getAttribute("iconsversion"));g_multifactorscore=parseInt(d[0].getAttribute("multifactorscore"));g_disablepwalerts=1==parseInt(d[0].getAttribute("disablepwalerts"));lpsendchallengescore=null!=d[0].getAttribute("sendchallengescore")&&1==d[0].getAttribute("sendchallengescore")?!0:!1;var f=d[0].getAttribute("pushserver");
null!=f&&f.length&&setup_push_listener(f);lpCheckDownloadNewDataFile(d[0].getAttribute("formfillver"),"ff.dat",ffver,"ff","ff.dat");lpCheckDownloadNewDataFile(d[0].getAttribute("sitesver"),"sites.dat",-1,"sites","sites.dat");""==d[0].getAttribute("privatekeyenchash")?have_binary_function("xGenerateKeys")?(d=AES.bin2hex(g_local_key).toUpperCase(),call_binary_function("xGenerateKeys",d,function(a){a=a.split("|");2==a.length&&upload_rsa_keys({privatekey:atob(a[0]),publickey:atob(a[1])})})):have_pplastpass()?
(d=AES.bin2hex(g_local_key).toUpperCase(),pplastpass_send_message({cmd:"xGenerateKeys",userkeyhex:d},function(a){a=a.split("|");2==a.length&&upload_rsa_keys({privatekey:atob(a[0]),publickey:atob(a[1])})})):g_ischrome&&(d=new RSAKey,generate_key(d,upload_rsa_keys)):readrsaprivatekeyhexfromdb(!1,!0,d[0].getAttribute("privatekeyenchash"));(!b||"boolean"==typeof c&&c)&&lpnp_notify("internal_logincheck_ack",{data0:lp_phpsessid,data1:g_username,data2:g_identity});d=a.responseXML.documentElement;d=d.getElementsByTagName("ok");
1==lpGetPref("storeLostOTP",1)&&(d[0].hasAttribute("lostpwotpresult")&&"ok"!=d[0].getAttribute("lostpwotpresult")&&!1==g_norecovery)&&(DeleteOTP(),MakeOTP());if(!hassites()||g_server_accts_version!=g_local_accts_version)console_log("server.js : !hassites() or server_ver:"+g_server_accts_version+" != local_ver:"+g_local_accts_version+" so calling get_accts_local!"),get_accts_local();checkIconsVersion(iconsversion);lpretryrequests();if(d[0].getAttribute("sauid0")){a=0;for(c="";d[0].getAttribute("sauid"+
a);)(b=lprsa_encryptdata(d[0].getAttribute("sakey"+a),AES.bin2hex(g_local_key)))&&(c+="&sauid"+a+"="+en(d[0].getAttribute("sauid"+a))+"&sakey"+a+"="+en(b)),a++;c.length&&lpMakeRequest(base_url+"uploadsuperkeys.php","cmd=uploadsuperadmin&"+c,null,null)}}
function lpCheckDownloadNewDataFile(a,c,b,d,f){if(!(""==a||0==a)){var e=b;c=localStorage.getItem(f);b=!1;null!=c&&""!=c&&"\n"!=c?(e=-1==c.indexOf("\n")?c.length:c.indexOf("\n"),e=c.substr(0,e)):b=!0;null!=e&&(""!=e&&-1!=e&&0<CompareLastPassVersions(a,e))&&(b=!0);b&&lpMakeRequest(base_url+"getappdata.php","type="+en(d),lpDownloadDataResponse,null,f)}}var adminoverride="",lplastgetaccounts=0;
function get_accts(){var a=(new Date).getTime();1E3>a-lplastgetaccounts||(lplastgetaccounts=a,a=base_url+"getaccts.php?mobile=1&b64=1&shap=1&u="+g_username_hash,a+="&includesharedfolderformfillprofiles=1",""!=adminoverride&&(a+="&adminoverride="+en(adminoverride)),lpMakeRequest(a,"",lpAcctsResponse,lpAcctsError))}function get_accts_local(a,c){lpReadAcctsData(a,c)}
function lpAcctsResponse(a){if(a&&4==a.readyState){a=atob(a.responseText);lp_enterpriseuser=lp_premium_exp=0;var c=get_ff_translation("ff_captcha_regexp");lp_captcha_regexp=""!=c?RegExp(c,"i"):null;parsemobile(a,a.length,100,0,postacctsload,[],[],[],[],[],[],[],!0,!1,null,[],[],[],[],[],[],lp_rsaprivatekeyhex,[],null,null,null,[],[],[],[]);g_premium_exp=lp_premium_exp;g_enterpriseuser=lp_enterpriseuser}}
function get_ff_translation(a){var c=lpGetPref("language","");""==c&&(c=navigator.language);var b=c,c=c.replace("-","_");if("es_419"==c||"es_419"==b||"es-419"==b||"es_xl"==c||"es_xl"==b||"es-xl"==b)c="es_MX",b="es-MX";"undefined"==typeof translations[c]&&"undefined"==typeof translations[b]&&(b=c=c.substring(0,2));if("undefined"==typeof translations[c]&&"undefined"==typeof translations[b])for(var d in translations)if(d.substring(0,2)==c){b=c=d;break}"undefined"==typeof translations[c]&&"undefined"==
typeof translations[b]&&(c="en_US",b="en-US");if("undefined"==typeof translations[c]&&"undefined"==typeof translations[b])for(d in b=c="en",translations)if(d.substring(0,2)==c){b=c=d;break}return"undefined"!=typeof translations[c]&&"undefined"!=typeof translations[c][a]&&""!=translations[c][a]?translations[c][a]:"undefined"!=typeof translations[b]&&"undefined"!=typeof translations[b][a]&&""!=translations[b][a]?translations[b][a]:"undefined"!=typeof translations.en_US&&"undefined"!=typeof translations.en_US[a]&&
""!=translations.en_US[a]?translations.en_US[a]:"undefined"!=typeof translations["en-US"]&&"undefined"!=typeof translations["en-US"][a]&&""!=translations["en-US"][a]?translations["en-US"][a]:""}
function rewritelocalfile(a,c,b){b="undefined"==typeof b?null:b;var d=flattendata(g_local_accts_version,g_sites,g_securenotes,g_prompts,g_formfills,g_identities,g_equivalentdomains,g_neverurls,g_premium_exp,lpenc(g_username),g_pendings,g_shareeautopushes,lpmaxid,g_urlrules,g_prefoverrides,g_shares,g_applications,g_enterpriseuser,lp_attaches),d=btoa(d);if(LPISLOC||b)d="LPB64"+d;d=prependOTPAndEncrypt(d);d=prependIterations(d);lpSaveData(d,"accts");if(LPISLOC||b){d=lpenc(d);d=prependIterations(d);if(b)return d;
protect_data(d,!0,null,function(d){if(have_binary_function("write_file")){var e="";a&&(e="_"+(new Date).toString().replace(" ","_"));e=db_prepend(g_username_hash+e+"_lps.act.sxml");b&&(e="lpexport.xml");call_binary_function("write_file",e,d)}!a&&!c&&lpnp_notify("refresh_local",{data0:g_username_hash})})}update_menus(!0)}
function prependOTPAndEncrypt(a){var c=null,b="";sesame_getdata("password_offline")&&""!=sesame_getdata("password_offline")?(lpdbg("sesame","encrypting accounts file before writing"),c=sesame_getdata("password_offline"),b="type=sesameoffline\ndata="):multifactor_getdata("password_offline")&&""!=multifactor_getdata("password_offline")?(lpdbg("multifactor","encrypting accounts file before writing"),c=multifactor_getdata("password_offline"),b="type="+multifactor_getdata("type")+"offline\ndata="):yubikey_getdata("password_offline")&&
""!=yubikey_getdata("password_offline")&&(lpdbg("yubikey","encrypting accounts file before writing"),c=yubikey_getdata("password_offline"),b="type=yubikeyoffline\ndata=");if(c){a=enc(a,hex2bin(c));if(!a||""==a)return lpdbg("error","Failed to encrypt data in save_accounts_fileraw"),!1;a=b+a}return a}
function clearSavedPassword(a){var c=opendb();createSavedLoginsTable(c);c&&c.transaction(function(b){console_log("server.js : clearing saved credentials");b.executeSql("UPDATE LastPassSavedLogins2 SET password = '' WHERE username = ?",[a])})}
function postacctsload(a,c,b,d,f,e,g,h,n,m,l,k,p,r,v,w,t,s,q,A,x,y){if(lploggedin)if(!h&&(!m||m&&0==a.length))console_log("server.js : ERROR: Could not parse accts data!!!"),gPulledInvalidAccts?lpshowError("ErrorGetAcctsMsg"):(gPulledInvalidAccts=!0,get_accts());else{try{if(null!=lp_trueapi_trial_exp){var z=parseInt(lp_trueapi_trial_exp);0<z&&z<parseInt((new Date).getTime()/1E3)&&(getsinglefactortype(function(a){"trueapi"==a&&setsinglefactortype("")}),"trueapi"==multifactor_getdata("type")&&multifactor_setdata("type",
""))}}catch(B){}if(0<a.length&&("undefined"!=typeof l&&null!=l&&""==adminoverride)&&(h=lpdec(l),""!=l&&null!=l&&"null"!=l&&g_username!=h))return lpReportError("Encrypted username check failed: "+g_username+" vs "+h+" for "+l+" local "+m,null),lpshowError("A consistency check failed while loading your sites. Please relogin."),clearSavedPassword(g_username),clearAllData(),loggedOut(!1,"encryptedusername_check_failed"),!1;lpmaxid=r.maxid;m||(g_local_accts_version=get_version(n),n=btoa(n),n=prependOTPAndEncrypt(n),
n=prependIterations(n),lpSaveData(n,"accts"));n=[];g_tlds=[];m=AES.bin2hex(g_local_key);for(var j=0;j<a.length;j++){a[j].url=AES.hex2url(a[j].url);a[j].tld=lp_gettld_url(a[j].url);if(LPISLOC&&a[j].tld)try{var u=function(){rfdefaults&&"undefined"!=typeof rfdefaults[a[j].tld]&&(a[j].submit_id=rfdefaults[a[j].tld].submit_id,a[j].captcha_id=rfdefaults[a[j].tld].captcha_id,a[j].custom_js=rfdefaults[a[j].tld].custom_js)};rfdefaults?u():lpReadFile("rfdefaults",function(a){rfdefaults=JSON.parse(lp_hex2bin(a));
u()})}catch(C){}l="undefined"==typeof a[j].sharefolderid?g_local_key:getsharekey(s,a[j].sharefolderid);null!=l&&(r="undefined"==typeof a[j].sharefolderid?m:AES.bin2hex(l),a[j].unencryptedUsername=lpmdec(a[j].username,!0,l,r));"undefined"==typeof g_tlds[a[j].tld]&&(g_tlds[a[j].tld]=[]);g_tlds[a[j].tld][a[j].aid]=!0;n[a[j].aid]=a[j]}m=[];for(j=0;j<c.length;j++)c[j].url=AES.hex2url(c[j].url),m[c[j].aid]=c[j];l=[];for(j=0;j<q.length;j++)q[j].appname=AES.hex2url(q[j].appname),l[q[j].appaid]=q[j];g_sites=
n;g_securenotes=m;g_applications=l;g_prompts=b;g_formfills=d;g_identities=f;g_equivalentdomains=e;g_urlrules=v;g_neverurls=g;g_pendings=k;g_prefoverrides=t;g_shares=s;lp_attaches=A;0<g_shares.length&&(("undefined"==typeof lp_rsaprivatekeyhex||null==lp_rsaprivatekeyhex||""==lp_rsaprivatekeyhex)&&"undefined"==typeof g_keyloopprotection)&&setTimeout(function(){lp_rsaprivatekeyhex&&""!=lp_rsaprivatekeyhex?(g_keyloopprotection=!0,get_accts_local()):(g_keyloopprotection=!0,readrsaprivatekeyhexfromdb(!0,
!0,null,function(){lp_rsaprivatekeyhex&&""!=lp_rsaprivatekeyhex&&get_accts()}))},5E3);overrideprefs(g_prefoverrides);setcachedffdat();g_shareeautopushes=[];parseAutoPushMobile(p,g_shareeautopushes);for(j=0;j<g_formfills.length;j++)g_formfills[j].decprofilename=lpmdec_acct(g_formfills[j].profilename,!0,g_formfills[j],g_shares);g_formfills.sort(function(a,b){return a.decprofilename.toLowerCase()<b.decprofilename.toLowerCase()?-1:1});b=!1;for(j=0;j<g_identities.length;j++)g_identities[j].deciname=lpdec(g_identities[j].iname),
g_identities[j].iid==g_identity&&(b=!0);g_identities.sort(function(a,b){return a.deciname.toLowerCase()<b.deciname.toLowerCase()?-1:1});if(!b&&""!=g_identity)return identityFilter="",switch_identity("",!0),clearCache(!0,!1,!1),setTimeout(function(){loggedOut(!1,"wrongidentity")},500),alertfrombg(gs("Your selected Identity no longer exists. Defaulting to 'All' and logging off.")),!1;rsa_acceptpendingshares();rsa_acceptshareeautopushes();u=function(a){a=(null==a?"":a).split("\n");for(var b=0;b<a.length;b++){var c=
a[b].split(" ");if(2==c.length&&""!=c[0]&&""!=c[1]){var d=c[0],c=c[1];g_sites[d]&&c>g_sites[d].last_touch&&(g_sites[d].last_touch=c)}}};b="";(g_is_win||g_is_mac&&LPISLOC)&&have_binary_function("read_file")?call_binary_function("read_file",db_prepend(g_username_hash+"_lt.cac"),u):("undefined"!=typeof localStorage&&(b=localStorage.getItem(db_prepend(g_username_hash+"_lt.cac"))),u(b));if("undefined"!=typeof foundmsfi){postdata="";for(j=0;j<msfids.length;j++){f=msfids[j].shareid;d="";for(b=0;b<g_shares.length;b++)if(g_shares[b].id==
f){d=AES.bin2hex(g_shares[b].key);decsharename=g_shares[b].decsharename;break}f=new RSAKey;parse_public_key(f,msfids[j].key)&&(d=f.encrypt(d),b=lpenc(decsharename,g_shares[b].key),postdata+="&sharekey"+j+"="+encodeURIComponent(d)+"&uid"+j+"="+encodeURIComponent(msfids[j].uid),postdata+="&shareid"+j+"="+encodeURIComponent(msfids[j].shareid),postdata+="&decsharename"+j+"="+encodeURIComponent(decsharename),postdata+="&encsharename"+j+"="+encodeURIComponent(b))}lpMakeRequest(base_url+"process_msf.php",
postdata,null,null)}console_log("server.js : num sites: "+a.length+" num sn: "+c.length+" num ff: "+g_formfills.length+" num identities: "+g_identities.length+" pendings: "+g_pendings.length+" num applications: "+g_applications.length);recheckall();update_menus(!0);"undefined"!=typeof x&&x.attachversion>lp_server_attach_version&&(lp_server_attach_version=x.attachversion);setTimeout(function(){checkAttach()},1E3);g_runchallenge&&setTimeout(function(){runChallenge()},1E4);"undefined"!=typeof y&&"function"==
typeof handle_pending_pushed_sites&&handle_pending_pushed_sites(y,function(){get_accts()},g_shares)}}function setcachedffdat(){for(var a=localStorage.getItem("ff.dat"),a=null==a?translations:LPJSON.parse(a),c=[],b=0;b<g_formfills.length;b++)c[lpmdec_acct(g_formfills[b].profilelanguage,!0,g_formfills[b],g_shares)]=1;var d=[];for(b in a)if("en-US"==b||"undefined"!=typeof c[b])d[b]=a[b];g_cachedffdat=LPJSON.stringify(d)}
function overrideprefs(a){if(typeof a.allowmasterpasswordsave&&"0"==a.allowmasterpasswordsave){lpPutGblPref("rememberpassword",0);g_master_password_saved=!1;var c=opendb();createSavedLoginsTable(c);c&&c.transaction(function(a){a.executeSql("UPDATE LastPassSavedLogins2 SET password = '' WHERE username = ?",[g_username])})}"undefined"!=typeof a.logoffclosebrowser&&"-1"!=a.logoffclosebrowser&&(lpPutGblPref("logoffWhenCloseBrowser",1),lpPutGblPref("logoffWhenCloseBrowserVal",a.logoffclosebrowser));"undefined"!=
typeof a.logoffidle&&"-1"!=a.logoffidle&&lpPutUserPref("idleLogoffVal",a.logoffidle);"undefined"!=typeof a.noexport&&"-1"!=a.noexport&&lpPutUserPref("noexport",a.noexport);lpWriteAllPrefs();LP.sitepwlen="string"==typeof a.sitepwlen&&""!=a.sitepwlen?JSON.parse(a.sitepwlen):[];"undefined"!=typeof a.hideidentities&&"-1"!=a.hideidentities&&(g_hideidentities="1"==a.hideidentities);g_savesitestopersonal="string"==typeof a.savesitestopersonal&&""!=a.savesitestopersonal?a.savesitestopersonal.split(","):[]}
function lpAcctsError(){L("Error xhr_accts")}function checkIconsVersion(a){var c=opendb();createDataTable(c);c?c.transaction(function(b){b.executeSql("SELECT * FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),"icons"],function(b,c){var e=!0,g=null;lpGetPref("icons",-1);0<c.rows.length&&lpGetPref("icons",-1)==a&&(e=!1,g=c.rows.item(0).data);null==g||e?downloadIcons():processIcons(g)},function(a,b){console_log(b)})}):downloadIcons()}
function processIcons(a){if(a)for(;!(10>a.length);){var c=/lp([^:]+):([^:]+):/.exec(a);if(!c||3!=c.length)break;var b=c[1],d=c[2],c=parseInt(d);if(isNaN(c))break;d="lp"+b+":"+d+":";g_icons[b]=lpsubstring(a,d.length,d.length+c);g_icons_length++;a=a.substring(d.length+c)}}function lpsubstring(a,c,b){var d="",f=b-c;for(b=0;b<f;++b)d+=a[b+c];return d}function downloadIcons(){lpMakeRequest(base_url+"geticon.php","versionchrome=1&username="+en(g_username),lpIconResponse,null)}
function lpIconResponse(a){if(4==a.readyState&&(200==a.status&&a.responseText)&&!("latest"==a.responsetext||"nodata"==a.responsetext)){var c=a.responseText.split("\n");a=c[0].split("=")[1];c=c[1];lpPutUserPref("icons",a);lpWriteAllPrefs();lpSaveData(c,"icons");processIcons(c)}}function loglogin(a){get_selected_tab(null,function(c){logloginurl(a,c)})}function loglogintab(a,c){("undefined"==typeof c.incognito||!c.incognito)&&logloginurl(a,gettaburl(c))}
function logloginurl(a,c){var b=lp_get_gmt_timestamp();if("undefined"!=typeof g_sites[a]){if(parseFloat(b)<5+parseFloat(g_sites[a].last_touch))return;g_sites[a].last_touch=b;writenewts(a,b)}else if("undefined"!=typeof g_securenotes[a]){if(b==g_securenotes[a].last_touch)return;g_securenotes[a].last_touch=lp_get_gmt_timestamp();rewritelocalfile();if(!g_loglogins||4!=(g_loglogins&4))return}if(g_loglogins){var b="id="+en(a)+"&method="+encodeURIComponent(get_method()),d=getacct(a);1<g_loglogins&&d&&(2==
(g_loglogins&2)&&"http://sn"!=d.url&&(b+="&u="+en(AES.url2hex(c))),4==(g_loglogins&4)&&(b+="&n="+en(AES.url2hex(d.name))),8==(g_loglogins&8)&&(b+="&un="+en(AES.url2hex(getusernamefromacct(d)))));d&&(d=issharedfolder(g_shares,d.group))&&(b+="&sharedfolderid="+en(d.id));lpMakeRequest(base_url+"loglogin.php",b,null,null)}}
function writenewts(a,c){var b=function(b){b=(null==b?"":b).split("\n");for(var d="",g=0;g<b.length;g++)0!=b[g].indexOf(a+" ")&&""!=b[g]&&(d+=b[g]+"\n");d+=a+" "+c+"\n";(g_is_win||g_is_mac&&LPISLOC)&&have_binary_function("write_file")&&call_binary_function("write_file",db_prepend(g_username_hash+"_lt.cac"),d);if("undefined"!=typeof localStorage)try{localStorage.setItem(db_prepend(g_username_hash+"_lt.cac"),d)}catch(h){L("Failed to setItem("+db_prepend(g_username_hash+"_lt.cac")+") e: "+h)}},d="";
(g_is_win||g_is_mac&&LPISLOC)&&have_binary_function("read_file")?call_binary_function("read_file",db_prepend(g_username_hash+"_lt.cac"),b):("undefined"!=typeof localStorage&&(d=localStorage.getItem(db_prepend(g_username_hash+"_lt.cac"))),b(d))}
function logformfill(a){get_selected_tab(null,function(c){if(("undefined"==typeof c.incognito||!c.incognito)&&g_loglogins){c="ffid="+en(a);for(var b=0;b<g_formfills.length;b++)if(g_formfills[b].ffid==a){(b=issharedfolder(g_shares,"undefined"!=typeof g_formfills[b].group?g_formfills[b].group:""))&&(c+="&sharedfolderid="+en(b.id));break}lpMakeRequest(base_url+"logformfill.php?"+c,"",null,null)}})}
function lpWriteKeyFile(){console_log("server.js : lpWriteKeyFile : start");var a=AES.bin2hex(g_local_key);if("undefined"!=typeof g_pwdeckey&&null!=g_pwdeckey){var a=AES.Encrypt({pass:g_pwdeckey,data:a,b64:!0,mode:"ecb",bits:256}),c=AES.Encrypt({pass:g_local_key,data:"lastpass rocks",b64:!0,mode:"ecb",bits:256}),a=a+"\n"+c;console_log("server.js : lpWriteKeyFile : calling lpSaveData");lpSaveData(a,"key");(g_is_win||g_is_mac||g_is_linux)&&have_binary_function("write_file")?(console_log("server.js : lpWriteKeyFile : calling protect_data"),
protect_data(a,!0,null,function(a){console_log("server.js : lpWriteKeyFile : protect_data callback");lpdisableoffline?console_log("server.js : lpWriteKeyFile : not writing keyfile since lpdisableoffline is true"):(console_log("server.js : lpWriteKeyFile : calling binary function to write keyfile"),call_binary_function("write_file",db_prepend(g_username_hash+"_lpall.slps"),a))})):console_log("server.js : lpWriteKeyFile : did not have binary function, so not writing")}else console_log("server.js : lpWriteKeyFile : not writing A")}
function lpReadKeyFile(a,c,b,d){console_log("server.js : lpReadKeyFile fromwebsite="+c+" silent="+b+" bIsLoginCheck="+d);b=opendb();createDataTable(b);b?(console_log("server.js : lpReadKeyFile : reading db"),b.transaction(function(b){console_log("server.js : lpReadKeyFile : starting db transaction");var e=function(b,e){console_log("server.js : lpReadKeyFile : reading numrows="+e.rows.length);if(0<e.rows.length){var f=e.rows.item(0).data;if(f)if(f=f.split("\n"),2==f.length){var g=null,g=a?AES.hex2bin(lpdec(f[0],
g_pwdeckey)):g_local_key;if("lastpass rocks"==lpdec(f[1],g)){g_local_key=g;g_local_key_hex=AES.bin2hex(g);g_local_key_hash=SHA256(g_local_key);if(a){console_log("server.js : lpReadKeyFile : worked -- calling lpLoginResponse_win2");lpLoginResponse_win2(a,c,d);return}loggedIn();console_log("server.js : lpReadKeyFile worked -- calling get_accts_local");get_accts_local(!0)}else console_log("server.js : lpReadKeyFile : data was corrupt A")}else console_log("server.js : lpReadKeyFile : data was corrupt B");
else console_log("server.js : lpReadKeyFile : did not find any data")}else console_log("server.js : lpReadKeyFile : failed to read -- calling lp_login_from_saved"),lp_login_from_saved();a&&loggedOut(!1,"keyfailed")},g=function(a,b){console_log("server.js : lpReadKeyFile failed error="+b)};LPISLOC?(console_log("server.js : lpReadKeyFile calling read_key_from_file"),read_key_from_file(function(a){console_log("server.js : lpReadKeyFile read_key_from_file callback");""!=a?e(b,{rows:{length:1,item:function(){return{data:a}}}}):
e(b,{rows:{length:0}})})):(console_log("server.js : lpReadKeyFile calling executeSql"),b.executeSql("SELECT * FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),"key"],e,g))})):console_log("server.js : lpReadKeyFile : failed to open database")}
function lpCheckForKey(a){var c=opendb();createDataTable(c);c&&c.transaction(function(b){var c=function(b,c){0<c.rows.length?a():console_log("no key")},f=function(a,b){console_log(b)};LPISLOC?read_key_from_file(function(a){""!=a?c(b,{rows:{length:1,item:function(){return{data:a}}}}):c(b,{rows:{length:0}})}):b.executeSql("SELECT * FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),"key"],c,f)})}
function lpReadAcctsData(a,c){if(!(null==g_username||""==g_username)){var b=opendb();createDataTable(b);b?b.transaction(function(b){var f=function(b,d){if(0<d.rows.length){if((data=d.rows.item(0).data)&&""!=data){data=checkIterationsInDataFile(data);if("iterationserror"==data){console_log("server.js : local accts data corrupt - key mismatch. redownloading");get_accts();return}if(a&&(!sesame_getdata("password_offline")||""==sesame_getdata("password_offline")||!yubikey_getdata("password_offline")||
""==yubikey_getdata("password_offline")||!multifactor_getdata("password_offline")||""==multifactor_getdata("password_offline"))){if(0==data.substring(0,30).indexOf("type=sesameoffline\ndata=")){sesame_setdata("offline","1");sesame_getotp(g_username);return}if(0==data.substring(0,30).indexOf("type=trueapioffline\ndata=")||0==data.substring(0,30).indexOf("type=omnikeyoffline\ndata=")){multifactor_setdata("offline","1");multifactor_setdata("type",0==data.substring(0,30).indexOf("type=trueapioffline\ndata=")?
"trueapi":"omnikey");multifactor_getresponse(g_username);return}if(0==data.substring(0,30).indexOf("type=yubikeyoffline\ndata=")){yubikey_setdata("offline","1");yubikey_getotp(g_username);return}}var e=null;sesame_getdata("password_offline")&&""!=sesame_getdata("password_offline")&&0==data.substring(0,30).indexOf("type=sesameoffline\ndata=")?(lpdbg("sesame","decrypting accounts file after reading"),data=data.substring(24),e=sesame_getdata("password_offline")):multifactor_getdata("password_offline")&&
""!=multifactor_getdata("password_offline")&&(0==data.substring(0,30).indexOf("type=trueapioffline\ndata=")||0==data.substring(0,30).indexOf("type=omnikeyoffline\ndata="))?(lpdbg("multifactor","decrypting accounts file after reading"),data=data.substring(25),e=multifactor_getdata("password_offline")):yubikey_getdata("password_offline")&&(""!=yubikey_getdata("password_offline")&&0==data.substring(0,30).indexOf("type=yubikeyoffline\ndata="))&&(lpdbg("yubikey","decrypting accounts file after reading"),
data=data.substring(25),e=yubikey_getdata("password_offline"));e&&(data=dec(data,hex2bin(e)))}LPISLOC&&(5<=data.length&&"LPB64"==data.substring(0,5))&&(data=data.substring(5));try{data=atob(data)}catch(f){console_log("server.js : local accts data corrupt. redownloading");get_accts();return}g_local_accts_version=get_version(data);g_local_accts_version!=g_server_accts_version&&-1!=g_server_accts_version?(console_log("server.js : local accts version is outdated: local:"+g_local_accts_version+" server:"+
g_server_accts_version+" redownloading"),get_accts()):(L("using cached accts data"),hassites()&&(!c||"refetchsharing"!=c)?L("Cached data already in place, ABORT, to avoid reparse."):(lp_enterpriseuser=lp_premium_exp=0,e=get_ff_translation("ff_captcha_regexp"),lp_captcha_regexp=""!=e?RegExp(e,"i"):null,parsemobile(data,data.length,100,0,postacctsload,[],[],[],[],[],[],[],!0,!0,null,[],[],[],[],[],[],lp_rsaprivatekeyhex,[],null,null,null,[],[],[],[]),g_premium_exp=lp_premium_exp,g_enterpriseuser=lp_enterpriseuser))}else g_username_hash&&
get_accts()},e=function(a,b){console_log(b)};LPISLOC?read_accts_from_file(function(a){""!=a?f(b,{rows:{length:1,item:function(){return{data:a}}}}):f(b,{rows:{length:0}})}):b.executeSql("SELECT * FROM LastPassData WHERE username_hash=? and type=?",[db_prepend(g_username_hash),"accts"],f,e)}):get_accts()}}
function MakeOTP(){if(!(null==g_username||0==g_username.length))if(!(null==g_local_key||0==g_local_key.length)){var a=fix_username(g_username);rng_seed_time();for(var c=[],b=0;16>b;b++)c[b]=0;rng_get_bytes(c);for(var d="",b=0;16>b;b++)d+=String.fromCharCode(c[b]);var c=enc(AES.bin2hex(d),g_local_key),f=make_lp_key(g_username,d),b=enc(AES.bin2hex(g_local_key),f),a=SHA256(SHA256(a+d)+d),e=AES.hex2bin(dec(b,f,1));g_local_key!=e?console_log("server.js : ERROR: Failed to decrypt newly encrypted key: dec_local_key:\n"+
AES.bin2hex(e)+" != \n"+AES.bin2hex(g_local_key)+"\nlen: "+e.length+" vs "+g_local_key.length+"\nrand pw:"+AES.bin2hex(d)+"\ng_username:"+g_username+"\nrand key:"+AES.bin2hex(f)+"\nrand_encrypted_key:"+b):(a="newkey=1&xml=1&hash="+LP.en(a),a+="&encrypted_otp="+LP.en(c),a+="&rand_encrypted_key="+LP.en(b),LP.lpMakeRequest(base_url+"otp.php",a+"&recovery=1",lpOTPUploadResponse,function(){},d))}}function DeleteOTP(){DeleteFromDB("otp")}
function DeleteFromDB(a){if(!(null==g_username||""==g_username))if(!LPISLOC||!("key"==a||"accts"==a)){var c=opendb();createDataTable(c);c&&c.transaction(function(b){b.executeSql("DELETE FROM LastPassData WHERE username_hash=? and type=?",[db_prepend(g_username_hash),a],function(){},function(a,b){console_log(b)})})}}
function GetOTPHash(a,c,b,d){a&&(a+="&outofbandsupported=1");var f=opendb();createDataTable(f);if(f){var e=b?SHA256(b):g_username_hash,g=b?b:g_username;f.transaction(function(b){b.executeSql("SELECT * FROM LastPassData WHERE username_hash=? and type=?",[db_prepend(e),"otp"],function(b,e){var f="";0<e.rows.length&&(f=e.rows.item(0).data);a?(""!=f?(f=AES.hex2bin(f),lostotphash=SHA256(SHA256(fix_username(g)+f)+f)):lostotphash="",1==lpGetPref("storeLostOTP",1)&&(a+="&lostpwotphash="+en(lostotphash)),
sesame_setdata("postdata",a),yubikey_setdata("postdata",a),googleauth_setdata("postdata",a),outofband_setdata("postdata",a),securityquestion_setdata("postdata",a),grid_setdata("postdata",a),multifactor_setdata("postdata",a),g_lastpoll=(new Date).getTime(),console_log("server.js : Requesting login.php A"),lpMakeRequest(base_url+"login.php",a,lpLoginResponse,lpLoginError)):c&&(lostotphash=""==f?"nouser":f,sendCS(c,{cmd:"recover",otp:lostotphash},d))},function(a,b){console_log(b)})})}else g_lastpoll=
(new Date).getTime(),console_log("server.js : Requesting login.php B"),lpMakeRequest(base_url+"login.php",a,lpLoginResponse,lpLoginError)}
function lpOTPUploadResponse(a,c,b){!lpdisableoffline&&(4==a.readyState&&200==a.status&&a.responseXML&&a.responseXML.documentElement)&&(a=opendb(),createDataTable(a),a&&a.transaction(function(a){a.executeSql("REPLACE INTO LastPassData (username_hash, type, data) VALUES (?, ?, ?)",[db_prepend(g_username_hash),"otp",AES.bin2hex(b)],function(){console_log("server.js : inserted")},function(a,b){console_log(b)})}))}
function savePassword(a,c,b,d){var f=lp_gettld_url(c);if(0==c.indexOf("chrome://")||0==c.indexOf("chrome-extension://"))f=c="Browser";f=gs("Generated Password for")+" "+f;a="url="+en(AES.url2hex(c))+"&password="+en(lpenc(a))+"&name="+en(lpenc(f));a+=get_identity_param();d&&(a+="&nofill=1");lpMakeRequest(base_url+"save_gen_pw.php",a,lpPopulateGeneratedPassword,null,b)}
function lpPopulateGeneratedPassword(a,c,b){if(4==a.readyState&&200==a.status&&a.responseXML&&a.responseXML.documentElement){a=a.responseXML.documentElement;c=a.getElementsByTagName("error");if(0<c.length&&(c=c[0].getAttribute("notloggedin"))&&"1"==c){loggedOut(!1,"lpPopulateGeneratedPassword");return}a=a.getElementsByTagName("ok");if(0<a.length){c=AES.hex2url(a[0].getAttribute("url"));var d=crypto_atob(a[0].getAttribute("password")),f={cmd:"populategeneratedpassword",url:c,password:lpmdec(d,!0),
nofill:a[0].getAttribute("nofill"),ff_currpass_regexp:get_ff_translation("ff_currpass_regexp")};sendCS(b,f,"all");b=createNewAcct();b.tld=lp_gettld_url(c);f=gs("Generated Password for")+" "+b.tld;b.aid=a[0].getAttribute("aid");"undefined"==typeof g_tlds[b.tld]&&(g_tlds[b.tld]=[]);g_tlds[b.tld][b.aid]=!0;add_ident_aid(b.aid);b.url=c;b.name=f;b.password=d;b.genpw=1;g_sites[b.aid]=b;g_local_accts_version++;rewritelocalfile();b=a[0].getAttribute("accts_version");compare_accounts_versions(b,g_local_accts_version)||
get_accts();refresh_windows()}}}function addeditformfill(a,c){var b="",d;for(d in a)b+=(""==b?"":"&")+d+"="+en(a[d]);d=issharedfolder(g_shares,"undefined"!=typeof c.group?c.group:"");b+=!1==d?"":"&sharedfolderid="+en(d.id);b+=get_identity_param();lpMakeRequest(base_url+"formfill.php",b,lpAddEditFormFillResponse,null,c)}
function deleteformfill(a,c){var b;if(!c)for(b=0;b<g_formfills.length;b++)if(g_formfills[b].ffid==a){if(g_formfills[b].pwprotect||g_prompts.view_ff_prompt){security_prompt(function(){deleteformfill(a,!0)});return}break}var d=!1;for(b=0;b<g_formfills.length;b++)if(g_formfills[b].ffid==a){d=issharedfolder(g_shares,"undefined"!=typeof g_formfills[b].group?g_formfills[b].group:"");g_formfills.splice(b,1);break}g_local_accts_version++;rewritelocalfile();b="deleteext=1&ffid="+LP.en(a);b+=!1==d?"":"&sharedfolderid="+
en(d.id);b+=get_identity_param();lpMakeRequest(base_url+"formfill.php",b,lpDeleteFormFillResponse,null,a)}
function lpAddEditFormFillResponse(a,c,b){if(4==a.readyState&&200==a.status&&a.responseXML&&a.responseXML.documentElement){a=a.responseXML.documentElement;c=a.getElementsByTagName("error");if(0<c.length&&(c=c[0].getAttribute("notloggedin"))&&"1"==c){loggedOut(!1,"lpAddEditFormFillResponse");return}c=a.getElementsByTagName("result");if(0<c.length){c[0].getAttribute("msg");a=c[0].getAttribute("ffid");var d=c[0].getAttribute("cfids");c=c[0].getAttribute("accts_version");for(var f=[],e=""==d?[]:d.split(","),
g=0,d=1;"undefined"!=typeof b["customfield"+d+"cfid"];++d){var h={};h.cfid=0!=b["customfield"+d+"cfid"]?b["customfield"+d+"cfid"]:g<e.length?e[g++]:0;h.text=b["customfield"+d+"text"];h.value=b["customfield"+d+"value"];h.alttext=b["customfield"+d+"alttext"];(""!=h.text||""!=h.value||""!=h.alttext)&&f.push(h)}e=b.cmd;delete b.cmd;delete b.deleteext;for(d=1;"undefined"!=typeof b["customfield"+d+"cfid"];++d)delete b["customfield"+d+"cfid"],delete b["customfield"+d+"text"],delete b["customfield"+d+"value"],
delete b["customfield"+d+"alttext"];b.custom_fields=f;if("add"==e)b.ffid=a,add_ident_ffid(a),g_formfills.push(b);else for(d=0;d<g_formfills.length;++d)if(a==g_formfills[d].ffid){g_formfills[d]=b;break}g_formfills.sort(function(a,b){return a.decprofilename.toLowerCase()<b.decprofilename.toLowerCase()?-1:1});g_local_accts_version++;rewritelocalfile();compare_accounts_versions(c,g_local_accts_version)||get_accts();refresh_windows();do_experimental_popupfill&&setTimeout(function(){recheckpage()},50)}}}
function lpDeleteFormFillResponse(a){if(4==a.readyState&&200==a.status&&a.responseXML&&a.responseXML.documentElement){a=a.responseXML.documentElement;var c=a.getElementsByTagName("error");if(0<c.length&&(c=c[0].getAttribute("notloggedin"))&&"1"==c){loggedOut(!1,"lpDeleteFormFillResponse");return}a=a.getElementsByTagName("result");0<a.length&&(a=a[0].getAttribute("accts_version"),compare_accounts_versions(a,g_local_accts_version)||get_accts(),refresh_windows(),do_experimental_popupfill&&setTimeout(function(){recheckpage()},
50))}}function saveSiteFromSubmit(a,c){a+="&auto=1"+get_identity_param();try{for(var b in g_sites)if(g_sites[b].genpw&&g_sites[b].tld==c.tld&&lpmdec_acct(g_sites[b].password,!0,g_sites[b],g_shares)==lpmdec_acct(c.password,!0,c,g_shares)){a+="&delgenpwaid="+LP.en(b);break}}catch(d){}c.postdata=a;c.posturl=base_url+"deliver_and_add.php";lpMakeRequest(base_url+"deliver_and_add.php",a,lpSaveSiteResponse,null,c)}
function updateFieldsFromSubmit(a,c){a+="&auto=1"+get_identity_param();lpMakeRequest(base_url+"gm_deliver.php",a,lpUpdateFieldsResponse,null,c)}function saveAllSite(a,c){a+="&auto=1"+get_identity_param();c.postdata=a;c.posturl=base_url+"show.php";lpMakeRequest(base_url+"show.php",a,lpSaveSiteResponse,null,c)}function saveSite(a,c){a+="&auto=1"+get_identity_param();c.postdata=a;c.posturl=base_url+(is_application(c)?"addapp.php":"show.php");lpMakeRequest(c.posturl,a,lpSaveSiteResponse,null,c)}
function openLinkedSites(a,c){setTimeout(function(){openchangepw(a,c)},700)}
function lpSaveSiteResponse(a,c,b){if(!rsa_shareeautopushesresponse(a,{url:b.posturl,aid:b.aid,postdata:b.postdata,handler:lpSaveSiteResponse,param:b,newvalues:b.newvalues})&&4==a.readyState&&200==a.status&&a.responseXML&&a.responseXML.documentElement){a=a.responseXML.documentElement;c=a.getElementsByTagName("error");if(0<c.length&&(c=c[0].getAttribute("notloggedin"))&&"1"==c){loggedOut(!1,"lpSaveSiteResponse");return}a=a.getElementsByTagName("result");if(0<a.length){"accountreplaced"==a[0].getAttribute("msg")&&
g_local_accts_version++;b.submit_id=a[0].getAttribute("submit_id");b.captcha_id=a[0].getAttribute("captcha_id");b.custom_js=a[0].getAttribute("custom_js");(c=a[0].getAttribute("attacherror"))&&""!=c&&alertfrombg(c);if("0"==b.aid){var d=a[0].getAttribute("aid"),f=a[0].getAttribute("urid");b.aid=b.fiid=d;b.urid=f;if(b.fields)for(var e=get_ff_translation("ff_captcha_regexp"),d=""!=e?RegExp(e,"i"):null,e=0;e<b.fields.length;e++)if(!b.fields[e].otherfield&&"1"!=b.fields[e].otherlogin&&(b.fields[e].urid=
f),d&&("undefined"==typeof b.captcha_id||""==b.captcha_id)&&"text"==b.fields[e].type&&d.exec(b.fields[e].name))b.captcha_id=b.fields[e].name;add_ident_aid(b.aid);if(b.sn)g_securenotes[b.aid]=b;else{if("undefined"==typeof b.tld||""==b.tld)b.tld=lp_gettld_url(b.url);"undefined"==typeof g_tlds[b.tld]&&(g_tlds[b.tld]=[]);g_tlds[b.tld][b.aid]=!0;g_sites[b.aid]=b}for(e in g_sites)g_sites[e].genpw&&(g_sites[e].tld==b.tld&&lpmdec_acct(g_sites[e].password,!0,g_sites[e],g_shares)==lpmdec_acct(b.password,!0,
b,g_shares))&&("undefined"!=typeof g_tlds[g_sites[e].tld]&&"undefined"!=typeof g_tlds[g_sites[e].tld][e]&&delete g_tlds[g_sites[e].tld][e],delete g_sites[e]);if("undefined"!=typeof b.attacharraychanges&&(!c||""==c)){if("undefined"!=typeof b.attacharraychanges.add)for(e in b.attacharraychanges.add)b.attacharraychanges.add.hasOwnProperty(e)&&(b.attacharraychanges.add[e].parent=b.aid,b.attacharraychanges.add[e].id=b.aid+"-"+b.attacharraychanges.add[e].id);applyattacharraychanges(b.attacharraychanges)}g_local_accts_version++;
rewritelocalfile()}else c&&""!=c&&"undefined"!=typeof b.attacharraychanges&&(rollbackattacharrayadds(b.attacharraychanges),rewritelocalfile());e=a[0].getAttribute("accts_version");compare_accounts_versions(e,g_local_accts_version)||get_accts();if("undefined"!=typeof b.retrieveattach&&1==b.retrieveattach){var g=function(){var a="version="+LP.en(lp_local_attach_version)+"&b64=1&chunked=1";LP.lpMakeRequest(LP.lp_base+"getattach.php",a,lpSaveAttach)};null==lp_local_attach_version||-1==lp_local_attach_version?
ReadFileGeneric(lpusername_hash+"_version.att",25,function(a){(lp_local_attach_version=a)||(lp_local_attach_version=0);g()}):g();b.retrieveattach=null}refresh_windows();do_experimental_popupfill&&(setTimeout(function(){recheckpage()},50),g_show_save_success_msg&&(doPopupSaveOK(g_popup_tabid_save),g_popup_tabid_save=null))}}}
function lpUpdateFieldsResponse(a,c,b){if(!rsa_shareeautopushesresponse(a,{url:b.posturl,aid:b.aid,postdata:b.postdata,handler:lpUpdateFieldsResponse,param:b,newvalues:b.newvalues})&&4==a.readyState&&200==a.status&&a.responseXML&&a.responseXML.documentElement){a=a.responseXML.documentElement;c=a.getElementsByTagName("error");if(0<c.length&&(c=c[0].getAttribute("notloggedin"))&&"1"==c){loggedOut(!1,"lpUpdateFieldsResponse");return}a=a.getElementsByTagName("ok");if(0<a.length){c=a[0].getAttribute("accts_version");
if(compare_accounts_versions(c,g_local_accts_version)){a=a[0].getAttribute("urid");c="0"==b.urid;var d=!c;c&&(b.urid=a);if(b.fields)for(var f=0;f<b.fields.length;f++)c&&!b.fields[f].otherfield&&"1"!=b.fields[f].otherlogin?b.fields[f].urid=a:d&&(!b.fields[f].otherfield&&"1"==b.fields[f].otherlogin&&"0"==b.fields[f].urid)&&(b.fields[f].urid=a)}else get_accts();refresh_windows()}}}
function addNever(a){g_neverurls.neveraccounts.push(a);g_local_accts_version++;rewritelocalfile();a="url="+en(url2hex(a));lpMakeRequest(base_url+"add_never.php",a,null,null)}
function deleteGroup(a,c,b,d,f,e){d="undefined"==typeof e?null:e;var g=issharedfolder(g_shares,a);e="";for(var h in g_sites)g_sites[h].group==a&&(e+=(""==e?"":",")+h);for(h in g_securenotes)g_securenotes[h].group==a&&(e+=(""==e?"":",")+h);for(h in g_applications)g_applications[h].group==a&&(e+=(""==e?"":",")+"app"+h);if(!1!=g&&(g=!1,-1==e.indexOf(",")&&e.length&&"undefined"!=typeof g_sites[e]&&"http://group"==g_sites[e].url&&(g=!0),!g)){alertfrombg("You cannot delete Shared folders.");return}if(""==
e&&!f)return deleteGroup("\\"+a,c,b,"deleteGroup",1,d);if(""==e&&1==f){if(null==d){console_log("server.js : Failed to find group and groupid is null");return}f=null;e="";for(h in g_sites)if(g_sites[h].id==d){f=g_sites[h].group;break}if(null==f)for(h in g_securenotes)if(g_securenotes[h].id==d){f=g_securenotes[h].group;break}if(null==f)for(h in g_applications)if(g_applications[h].id==d){f=g_applications[h].group;break}if(null!=f){for(h in g_sites)g_sites[h].group==a&&(e+=(""==e?"":",")+h);for(h in g_securenotes)g_securenotes[h].group==
a&&(e+=(""==e?"":",")+h);for(h in g_applications)g_applications[h].group==a&&(e+=(""==e?"":",")+"app"+h)}""==e&&(e=d,console_log("server.js : Still couldn't find stuff -- just using the passed groupid : aids="+e))}return deleteAid(e,c,!1,!1,b,a)}
function checkmultiplefolders(a){for(var c=!1,b=null,d=!0,f=0;f<a.length;f++){var e=get_record(a[f]);if(e)if(issharedfolder(g_shares,e.group))if(c){d=!1;break}else if(null==b)b=e.group;else{if(b!=e.group){d=!1;break}}else if(null!=b){d=!1;break}else c=!0}d||alertfrombg(gs("Sorry, you cannot perform this operation on a mix of shared and non-shared folders, or multiple shared folders at once."));return d}
function deleteAid(a,c,b,d,f,e){var g=a.split(",");if(!checkmultiplefolders(g))return!1;for(var h="",n=0,m=0;m<g.length;m++){var l=g[m];if(is_application(l)){if(!check_ident_appaid(l))continue}else if(!check_ident_aid(l))continue;var k,p;is_application(l)?(k=get_record(l),p=!1):(k=g_sites[l],p=g_prompts.edit_site_prompt,k||(p=g_prompts.edit_sn_prompt,k=g_securenotes[l]));if(k){h+=(""==h?"":",")+l;if("undefined"!=typeof k.sharefolderid&&(n=k.sharefolderid,l=issharedfolder(g_shares,k.group),!checkreadonly(l)))return!1;
if(!b&&(k.pwprotect||p))return security_prompt(function(){deleteAid(a,c,!0,d,f)}),!1}}if(""==h)return!1;m=gs("Are you sure you would like to delete this site?");k.genpw?m=gs("Are you sure you would like to delete this generated password?"):k.sn?m=gs("Are you sure you would like to delete this secure note?"):is_application(k)&&(m=gs("Are you sure you would like to delete this application?"));m+=" ("+k.name+")";1<g.length&&(m=gs("Are you sure you would like to delete the selected items?"));e&&(m=gs("Are you sure you would like to delete this group?")+
" ("+e+")");if(!d)if(null==c){if(!g_isopera&&!confirm(m))return!1}else if(!g_isopera&&!c.confirm(m))return!1;e=h.split(",");for(m=0;m<e.length;m++)if(l=e[m],is_application(l))delete g_applications[get_appaid(l)];else{if(!k.sn)try{delete g_tlds[k.tld][l]}catch(r){}delete g_sites[l];delete g_securenotes[l]}g_local_accts_version++;rewritelocalfile();h="ajax=1&extjs=1&delete=1&aid="+en(h);h+=get_identity_param();0!=n&&(h+="&sharedfolderid="+en(n));lpMakeRequest(base_url+"show.php",h,lpDeleteResponse);
f&&f();return!0}function lpDeleteResponse(a){a&&(4==a.readyState&&200==a.status&&null!=a.responseXML&&null!=a.responseXML.documentElement)&&(a=a.responseXML.documentElement.getElementsByTagName("result"),0<a.length&&(a=a[0].getAttribute("accts_version"),compare_accounts_versions(a,g_local_accts_version)||get_accts(),refresh_windows()))}
function editAid(a,c,b){if(check_ident_aid(a)){var d,f;is_application(a)?(d=get_record(a),f=!1):(d=g_sites[a],f=g_prompts.edit_site_prompt,d||(f=g_prompts.edit_sn_prompt,d=g_securenotes[a]));if(d)if(!b&&(d.pwprotect||f))security_prompt(function(){editAid(a,c,!0)});else{g_site_data=[];for(var e in d)g_site_data[e]=d[e];var g=0;b=!1;if("undefined"!=typeof d.attachpresent&&"1"==d.attachpresent){g_site_data.attaches=[];for(e in lp_attaches)lp_attaches[e].parent==a&&g++;for(e in lp_attaches)lp_attaches[e].parent==
a&&(0==lp_attaches[e].mimetype.indexOf("data:image")?(b=!0,function(a){lpReadAttach(lp_attaches[a].id,function(b){null!=b?g_site_data.attaches[g_site_data.attaches.length]={id:lp_attaches[a].id,mimetype:lp_attaches[a].mimetype,bytes:b}:g--;g_site_data.attaches.length==g&&openURL(getchromeurl("site.html"))})}(e)):(g_site_data.attaches[g_site_data.attaches.length]={id:lp_attaches[e].id,mimetype:lp_attaches[e].mimetype,bytes:null},b&&g_site_data.attaches.length==g&&openURL(getchromeurl("site.html"))))}b||
openURL(getchromeurl("site.html"))}}}function saveFields(a,c,b){b.handler=lpSaveFieldsResponse;if("undefined"!=typeof b.newvalues&&"undefined"==typeof b.newvalues.length){var d=b.newvalues,f=[],e;for(e in d)f.push(d[e]);b.newvalues=f}lpMakeRequest(base_url+"fields.php?"+a,c,lpSaveFieldsResponse,null,b)}
function lpSaveFieldsResponse(a,c,b){if(!(null!=b&&rsa_shareeautopushesresponse(a,b))&&4==a.readyState&&200==a.status&&a.responseXML&&a.responseXML.documentElement){a=a.responseXML.documentElement;c=a.getElementsByTagName("response");0<c.length&&(c=c[0].getAttribute("message"),console_log("server.js : Save Fields failed: "+c));c=a.getElementsByTagName("error");if(0<c.length&&(c=c[0].getAttribute("notloggedin"))&&"1"==c){loggedOut(!1,"lpSaveFieldsResponse");return}a=a.getElementsByTagName("result");
0<a.length&&(a=a[0].getAttribute("accts_version"),compare_accounts_versions(a,g_local_accts_version)||get_accts(),refresh_windows())}}
function poll_server_request(){if(lploggedin&&null==grid_getdata("active")){var a=base_url+"poll_server.php",c="";lpsendmpstrength&&null!=lpmpstrength&&(c+="&mpstrength="+LP.en(lpmpstrength));if(!0==g_prompts.improve)for(var b in g_events)g_events.hasOwnProperty(b)&&(c+="&"+LP.en(b)+"="+LP.en(g_events[b]));g_events=[];lpMakeRequest(a,c,poll_server_response,null);g_lastpoll=(new Date).getTime()}}
function poll_server(){if(!g_nopoll){if(lploggedin&&null==grid_getdata("active")){var a=(new Date).getTime();g_lastpollcheck=a;1==lpGetPref("logoffWhenCloseBrowser",0)&&0<lpGetPref("logoffWhenCloseBrowserVal",0)&&(lpPutUserPref("lastpollcheck",g_lastpollcheck),lpWriteAllPrefs());var c=60*parseInt(lpGetPref("pollServerVal",15)),b=1E3*c,d=function(c){if("locked"==c||"idle"==c)b*=g_logoff_other_ses?12:60;a-g_lastpoll>=b&&poll_server_request()};if(0<b){var f=function(a){a?call_binary_function("get_idle_ms",
function(a){d(a>=b?"idle":"active")}):enable_native_idle&&"undefined"!=typeof chrome&&"undefined"!=typeof chrome.idle?chrome.idle.queryState(c,d):d("active")};have_binary_function("get_idle_ms")?can_check_idle(f):f(!1)}}setTimeout(function(){poll_server()},6E4)}}var g_notifications=[];
function handlenotifications(a,c,b){try{if(lplog("notify: title="+a+" text="+c+" url="+b),webkitNotifications)if(0!=webkitNotifications.checkPermission())lplog("notify: requesting permission"),webkitNotifications.requestPermission(function(){lplog("notify: requesting permission callback called")});else{var d=webkitNotifications.createNotification("images/icon48.png",a,c);if(d){var f=(new Date).getTime()+"_"+Math.floor(100*Math.random());d.ondisplay=function(){lplog("notify: displaying notification id="+
f)};d.onclose=function(){lplog("notify: closing notification id="+f)};d.onclick=function(){lplog("notify: user clicked notification id="+f);b&&""!=b&&(lplog("notify: opening notication url for id="+f+" url="+b),d.cancel(),openURL(b))};d.show();g_notifications.push({id:f,time:(new Date).getTime(),note:d});1==g_notifications.length&&setTimeout(function(){notifications_autoclose()},0)}else lplog("notify: error : failed to create notification")}else lplog("notify: error: webkitNotifications is null")}catch(e){}}
function notifications_autoclose(){}function notifications_closeall(){lplog("notify: closing all notifications");for(var a=0;a<g_notifications.length;++a)lplog("notify: closing notification id="+g_notifications[a].id),g_notifications[a].note.cancel();g_notifications=[]}
function poll_server_response(a){if(4==a.readyState)if(200==a.status&&null!=a.responseXML&&null!=a.responseXML.documentElement){if(a=a.responseXML.documentElement.getElementsByTagName("ok"),0<a.length){g_logoff_other_ses="1"==a[0].getAttribute("logoff_other_ses")?!0:!1;var c=a[0].getAttribute("accts_version");g_server_accts_version=c;c>g_local_accts_version&&get_accts();var b=a[0].getAttribute("attachversion"),d=function(){if(b>lp_local_attach_version){var a="version="+LP.en(lp_local_attach_version)+
"&b64=1&chunked=1";LP.lpMakeRequest(LP.lp_base+"getattach.php",a,lpSaveAttach)}};null==lp_local_attach_version||-1==lp_local_attach_version?ReadFileGeneric(lpusername_hash+"_version.att",25,function(a){(lp_local_attach_version=a)||(lp_local_attach_version=0);d()}):d();lpsendmpstrength=null!=a[0].getAttribute("sendmpstrength")?!0:!1;if((c=a[0].getAttribute("note_title"))&&c.length){var f=a[0].getAttribute("note_text");a=a[0].hasAttribute("note_url")?a[0].getAttribute("note_url"):null;handlenotifications(c,
f,a)}}}else lpReportError("Problem in poll_server_response. status="+a.status,null)}
function upgrade_response(a){if(4==a.readyState)if(200==a.status&&null!=a.responseXML&&null!=a.responseXML.documentElement)if(a=a.responseXML.documentElement.getElementsByTagName("updatecheck"),0<a.length?(upgrade="1"==a[0].getAttribute("upgrade")?!0:!1,upgradeurl=a[0].getAttribute("codebase")):(upgrade=!1,upgradeurl=""),g_ischrome)g_notification_type="upgrade",g_notification_data={upgrade:upgrade,upgradeurl:upgradeurl},sendTS({cmd:"notification",type:"upgrade"});else{if(g_issafari||g_isopera||g_ismaxthon)upgrade?
confirm(gs("An Update is Available. Would you like to install?"))&&openURL(upgradeurl):alertfrombg(gs("No Updates Are Available"))}else lpReportError("Problem in upgrade_response. status="+a.status,null)}
function changePassword(a,c){var b=[];b.push(a);for(var d=[],f=0,e=0;e<c.length;e++)lpmdec_acct(g_sites[c[e]].password,!0,g_sites[c[e]],g_shares)!=a&&(d[d.length]=c[e]),"undefined"!=typeof g_sites[c[e]].sharefolderid&&(f=g_sites[c[e]].sharefolderid);c=d;if(0!=c.length){for(var d="xml=1",g=[],e=0;e<c.length;e++){var h=0<e?e:"",d=d+("&username"+h+"=dummy"),d=d+("&password"+h+"="+LP.en(lpenc_acct(a,g_sites[c[e]],g_shares))),d=d+("&id"+h+"="+LP.en(c[e]));b.push(a);try{lp_in_array(g_sites[c[e]].tld,g)||
(g[g.length]=g_sites[c[e]].tld)}catch(n){}}try{for(e in g_sites)if(g_sites[e].genpw&&lp_in_array(g_sites[e].tld,g)&&lpmdec_acct(g_sites[e].password,!0,g_sites[e],g_shares)==a){d+="&delgenpwaid="+LP.en(e);break}}catch(m){}0!=f&&(d+="&sharedfolderid="+en(f));f={aid:0};f.postdata=d;f.url=base_url+"change_pw.php";f.newvalues=b;f.handler=lpChangePasswordResponse;f.param={aid:f.aid,postdata:f.postdata,url:f.url,newvalues:f.newvalues,handler:f.handler};lpMakeRequest(f.url,f.postdata,f.handler,null,f)}}
function lpChangePasswordResponse(a,c,b){if(!rsa_shareeautopushesresponse(a,b)&&(4==a.readyState&&200==a.status&&a.responseXML&&a.responseXML.documentElement)&&(a=a.responseXML.documentElement.getElementsByTagName("ok"),0<a.length)){c=crypto_atob(a[0].getAttribute("newpassword"));b=[];for(var d="";a[0].hasAttribute("oldpassword"+d);){var f=parseInt(a[0].getAttribute("id"+d)),e=crypto_atob(a[0].getAttribute("oldpassword"+d)),f=g_sites[f];lp_in_array(f.tld,b)||(b[b.length]=f.tld);f.password==e&&(f.password=
c);if(f.fields)for(var g=0;g<f.fields.length;g++)"password"==f.fields[g].type&&f.fields[g].value==e&&(f.fields[g].value=c);""==d?d=1:d++}for(g in g_sites)g_sites[g].genpw&&(lp_in_array(g_sites[g].tld,b)&&lpmdec_acct(g_sites[g].password,!0,g_sites[g],g_shares)==lpmdec(c,!0))&&("undefined"!=typeof g_tlds[g_sites[g].tld]&&"undefined"!=typeof g_tlds[g_sites[g].tld][g]&&delete g_tlds[g_sites[g].tld][g],delete g_sites[g]);g_local_accts_version++;rewritelocalfile();g=a[0].getAttribute("accts_version");compare_accounts_versions(g,
g_local_accts_version)||get_accts()}}var lpyubidata={};function yubikey_getotp(){grid_setdata("active","1");lpdbg("yubikey","Asking user for fresh otp");openURL(getchromeurl("lp_toolstrip.html?browseraction=1&yubikey=1"));return""}function yubikey_setdata(a,c){lpyubidata[a]=c}function yubikey_getdata(a){return"undefined"==typeof lpyubidata[a]?null:lpyubidata[a]}function yubikey_cleardata(){lpdbg("yubikey","clearing data");lpyubidata={}}
function yubikey_auth(a,c){grid_setdata("active",null);if(""!=a)if("1"==yubikey_getdata("offline")){var b=a.substring(0,12);a=SHA256(SHA256(SHA256(fix_username("LastPassIsGreat")+b)+b));yubikey_setdata("password_offline",a);offlineloginsuccessful("offline",0);lpReadAcctsData();yubikey_setdata("offline","0")}else{var d=b=null,f=null,e=null;yubikey_getdata("postdata")?(b=yubikey_getdata("postdata")+"&otp="+encodeURIComponent(a),d="login.php",f=lpLoginResponse,e=lpLoginError):(b=sesame_getdata("logincheckpostdata")+
"&otp="+encodeURIComponent(a),d="login_check.php",f=lpLoginCheckResponse,e=lpLoginCheckError);""!=c&&(b+="&trustlabel="+encodeURIComponent(c));var g=yubikey_getdata("fromwebsite");console_log("server.js : Requesting "+d+" C");lpMakeRequest(base_url+d,b,f,e,g)}else lpshowError("LoginError",!1,!0),loggedOut(!1,"yubikey_auth_error")}var lpgoogleauthdata={};
function googleauth_getotp(){grid_setdata("active","1");lpdbg("googleauth","Asking user for fresh otp");openURL(getchromeurl("lp_toolstrip.html?browseraction=1&googleauth=1"));return""}function googleauth_setdata(a,c){lpgoogleauthdata[a]=c}function googleauth_getdata(a){return"undefined"==typeof lpgoogleauthdata[a]?null:lpgoogleauthdata[a]}function googleauth_cleardata(){lpdbg("googleauth","clearing data");lpgoogleauthdata={}}
function googleauth_auth(a,c){grid_setdata("active",null);if(""!=a)if("1"==googleauth_getdata("offline")){var b=a.substring(0,12);a=SHA256(SHA256(SHA256(fix_username("LastPassIsGreat")+b)+b));googleauth_setdata("password_offline",a);offlineloginsuccessful("offline",0);lpReadAcctsData();googleauth_setdata("offline","0")}else{var d=b=null,f=null,e=null;googleauth_getdata("postdata")?(b=googleauth_getdata("postdata")+"&otp="+encodeURIComponent(a),d="login.php",f=lpLoginResponse,e=lpLoginError):(b=sesame_getdata("logincheckpostdata")+
"&otp="+encodeURIComponent(a),d="login_check.php",f=lpLoginCheckResponse,e=lpLoginCheckError);""!=c&&(b+="&trustlabel="+encodeURIComponent(c));var g=googleauth_getdata("fromwebsite");console_log("server.js : Requesting "+d+" C");lpMakeRequest(base_url+d,b,f,e,g)}else lpshowError("LoginError",!1,!0),loggedOut(!1,"googleauth_auth_error")}var lpoutofbanddata={};
function outofband_getotp(a,c){grid_setdata("active","1");lpdbg("outofband","Asking user for fresh otp");g_trustlabel="";"1"==c.getAttribute("preferduowebsdk")?(lpTurnOffIcon(),openbaseurl("duo.php?username="+encodeURIComponent(g_username))):openURL(getchromeurl("lp_toolstrip.html?browseraction=1&outofband=1&capabilities="+encodeURIComponent(c.getAttribute("capabilities"))+"&allowtrust="+encodeURIComponent(c.getAttribute("allowtrust"))+"&smshash="+encodeURIComponent(c.getAttribute("smshash"))+"&smstime="+
encodeURIComponent(c.getAttribute("smstime"))+"&smsuid="+encodeURIComponent(c.getAttribute("smsuid"))+"&outofbandimage="+encodeURIComponent(c.getAttribute("outofbandimage"))+"&sms_nextcode="+encodeURIComponent(c.getAttribute("sms_nextcode"))));return""}function outofband_setdata(a,c){lpoutofbanddata[a]=c}function outofband_getdata(a){return"undefined"==typeof lpoutofbanddata[a]?null:lpoutofbanddata[a]}function outofband_cleardata(){lpdbg("outofband","clearing data");lpoutofbanddata={}}
var g_last_otpcheck,g_otpcheck_complete=!1,g_otpwin_closed=!1,g_trustlabel="";
function outofband_handler(a,c,b){if(!g_otpwin_closed)if(a&&4==a.readyState&&200==a.status&&0<a.responseText.indexOf("outofbandrequired")){if(null!=a.responseXML&&null!=a.responseXML.documentElement&&(a=a.responseXML.documentElement.getElementsByTagName("error"),0<a.length&&(a=a[0].getAttribute("retryid"))&&""!=a&&5E3<=(new Date).getTime()-g_last_otpcheck))postdata=outofband_getdata("postdata")+"&outofbandrequest=1&outofbandretry=1&outofbandretryid="+encodeURIComponent(a),g_last_otpcheck=(new Date).getTime(),
lpMakeRequest(base_url+"login.php",postdata,outofband_handler,c,b)}else g_otpcheck_complete=!0,closecurrenttab("lp_toolstrip.html?browseraction=1&outofband=1"),lpLoginResponse(a,c,b),""!=g_trustlabel&&(null!=a.responseXML&&null!=a.responseXML.documentElement&&0<a.responseXML.documentElement.getElementsByTagName("ok").length)&&getuuid(function(a){lpMakeRequest(LP.lp_base+"trust.php","uuid="+encodeURIComponent(a)+"&trustlabel="+encodeURIComponent(g_trustlabel));g_trustlabel=""})}
function outofband_auth(a,c){grid_setdata("active",null);if(""!=a)if(g_otpcheck_complete="dummy"!=a,g_otpwin_closed="dummy"!=a,"1"==outofband_getdata("offline")){var b=a.substring(0,12);a=SHA256(SHA256(SHA256(fix_username("LastPassIsGreat")+b)+b));outofband_setdata("password_offline",a);offlineloginsuccessful("offline",0);lpReadAcctsData();outofband_setdata("offline","0")}else{var d=b=null,f=null;outofband_getdata("postdata")?(b=outofband_getdata("postdata"),d="login.php",f=lpLoginError):(b=sesame_getdata("logincheckpostdata"),
d="login_check.php",f=lpLoginCheckError);"dummy"!=a&&(b+="&otp="+encodeURIComponent(a));""!=c&&(b+="&trustlabel="+encodeURIComponent(c));var b=b+"&outofbandrequest=1",e=outofband_getdata("fromwebsite");console_log("server.js : Requesting "+d+" C");g_last_otpcheck=(new Date).getTime();lpMakeRequest(base_url+d,b,"dummy"==a?outofband_handler:lpLoginResponse,f,e)}else g_otpcheck_complete||(g_otpwin_closed=!0,lpshowError("LoginError",!1,!0),loggedOut(!1,"outofband_auth_error"))}
var lpsecurityquestiondata={};
function securityquestion_getotp(a,c){if(c.getAttribute("redirecturl"))openURL(c.getAttribute("redirecturl"));else return grid_setdata("active","1"),lpdbg("securityquestion","Asking user for fresh otp"),getuuid(function(a){openURL(getchromeurl("lp_toolstrip.html?browseraction=1&securityquestion=1&uuid="+encodeURIComponent(a)+"&question="+encodeURIComponent(c.getAttribute("question"))+"&autotrust="+encodeURIComponent(c.getAttribute("autotrust"))+"&hidedisable="+encodeURIComponent(c.getAttribute("hidedisable"))+"&reseturl="+
encodeURIComponent(c.getAttribute("reseturl"))));securityquestion_setdata("reseturl",c.getAttribute("reseturl"))}),""}function securityquestion_setdata(a,c){lpsecurityquestiondata[a]=c}function securityquestion_getdata(a){return"undefined"==typeof lpsecurityquestiondata[a]?null:lpsecurityquestiondata[a]}function securityquestion_cleardata(){lpdbg("securityquestion","clearing data");lpsecurityquestiondata={}}
function securityquestion_auth(a,c){grid_setdata("active",null);if(""!=a)if("1"==securityquestion_getdata("offline")){var b=a.substring(0,12);a=SHA256(SHA256(SHA256(fix_username("LastPassIsGreat")+b)+b));securityquestion_setdata("password_offline",a);offlineloginsuccessful("offline",0);lpReadAcctsData();securityquestion_setdata("offline","0")}else{var d=b=null,f=null,e=null;securityquestion_getdata("postdata")?(b=securityquestion_getdata("postdata")+"&otp="+encodeURIComponent(a),d="login.php",f=lpLoginResponse,
e=lpLoginError):(b=sesame_getdata("logincheckpostdata")+"&otp="+encodeURIComponent(a),d="login_check.php",f=lpLoginCheckResponse,e=lpLoginCheckError);""!=c&&(b+="&trustlabel="+encodeURIComponent(c));var g=securityquestion_getdata("fromwebsite");console_log("server.js : Requesting "+d+" C");lpMakeRequest(base_url+d,b,f,e,g)}else lpshowError("LoginError",!1,!0),loggedOut(!1,"securityquestion_auth_error")}var lpsesamedata={},lpsesameotp=null;
function sesame_setotp(a){lpdbg("sesame","browser forwarded OTP => sesame_setotp called");lpsesameotp=a}function sesame_getotp(a){grid_setdata("active","1");if(a&&lpsesameotp)return lpdbg("sesame","Not requesting OTP - using value passed to browser"),a=lpsesameotp,lpsesameotp=null,sesame_auth(a,""),a;lpdbg("sesame","Asking user for fresh otp");openURL(getchromeurl("lp_toolstrip.html?browseraction=1&sesame=1"));return""}function sesame_setdata(a,c){lpsesamedata[a]=c}
function sesame_getdata(a){return"undefined"==typeof lpsesamedata[a]?null:lpsesamedata[a]}function sesame_cleardata(){lpdbg("sesame","clearing data");lpsesamedata={}}
function sesame_auth(a,c){grid_setdata("active",null);if(""!=a)if("1"==sesame_getdata("offline"))sesame_setdata("password_offline",a),offlineloginsuccessful("offline",0),lpReadAcctsData(),sesame_setdata("offline","0");else{var b=null,d=null,f=null,e=null;sesame_getdata("postdata")?(b=sesame_getdata("postdata")+"&sesameotp="+encodeURIComponent(a),d="login.php",f=lpLoginResponse,e=lpLoginError):(b=sesame_getdata("logincheckpostdata")+"&sesameotp="+encodeURIComponent(a),d="login_check.php",f=lpLoginCheckResponse,
e=lpLoginCheckError);""!=c&&(b+="&trustlabel="+encodeURIComponent(c));var g=sesame_getdata("fromwebsite");console_log("server.js : Requesting "+d+" D");lpMakeRequest(base_url+d,b,f,e,g)}else lpshowError("LoginError",!1,!0),loggedOut(!1,"sesame_auth_error")}var lpgriddata={},lpgridvalues=null;function grid_getvalues(a,c){grid_setdata("active","1");openURL(getchromeurl("lp_toolstrip.html?browseraction=1&grid=1&challenge="+encodeURIComponent(c)))}function grid_setdata(a,c){lpgriddata[a]=c}
function grid_getdata(a){return"undefined"==typeof lpgriddata[a]?null:lpgriddata[a]}function grid_cleardata(){lpdbg("grid","clearing data");lpgriddata={}}
function grid_auth(a,c){grid_setdata("active",null);if(""!=a){var b=null,d=null,f=null,e=null;grid_getdata("postdata")?(b=grid_getdata("postdata")+"&gridresponse="+encodeURIComponent(a),d="login.php",f=lpLoginResponse,e=lpLoginError):(b=sesame_getdata("logincheckpostdata")+"&gridresponse="+encodeURIComponent(a),d="login_check.php",f=lpLoginCheckResponse,e=lpLoginCheckError);""!=c&&(b+="&trustlabel="+encodeURIComponent(c));grid_getdata("wxsessid")&&(b+="&wxsessid="+encodeURIComponent(grid_getdata("wxsessid")));
var g=grid_getdata("fromwebsite");console_log("server.js : Requesting "+d+" E");lpMakeRequest(base_url+d,b,f,e,g)}else lpshowError("LoginError",!1,!0),loggedOut(!1,"grid_auth_error")}var lpmultifactordata={},lpmultifactorresponse=null;
function multifactor_getresponse(a,c){var b="";multifactor_setdata("active","1");var d=multifactor_getdata("type"),f="";multifactor_getdata("type")==d&&(f=multifactor_getdata("password_offline"));if(!f||64!=f.length)f=SHA256(SHA256(fix_username(a)+d));var e=function(){multifactor_setdata("password_offline",f);multifactor_setdata("type",d);if(c){if("omnikey"==d){omnikey_get_pin(function(a){have_binary_function("omnikey_decrypt")?call_binary_function("omnikey_decrypt",c,a,function(a){b=a;multifactor_auth(b,
"")}):multifactor_auth(b,"")});return}b=""!=f?SHA256(f+c):""}else b=f;multifactor_auth(b,"")};(!f||64!=f.length)&&"trueapi"==d&&have_binary_function("trueapi_get_hash")?call_binary_function("trueapi_get_hash",a,function(a){f=a;e()}):e()}function multifactor_setdata(a,c){lpmultifactordata[a]=c}function multifactor_getdata(a){return"undefined"==typeof lpmultifactordata[a]?null:lpmultifactordata[a]}function multifactor_cleardata(){lpdbg("multifactor","clearing data");lpmultifactordata={}}
function multifactor_auth(a,c){multifactor_setdata("active",null);if(""!=a)if("1"==multifactor_getdata("offline"))multifactor_setdata("password_offline",a),"omnikey"!=multifactor_getdata("type")&&multifactor_setdata("type","trueapi"),offlineloginsuccessful("offline",0),lpReadAcctsData(),multifactor_setdata("offline","0");else{var b=null,d=null,f=null,e=null;multifactor_getdata("postdata")?(b=multifactor_getdata("postdata")+"&multifactorresponse="+encodeURIComponent(a),d="login.php",f=lpLoginResponse,
e=lpLoginError):(b=sesame_getdata("logincheckpostdata")+"&multifactorresponse="+encodeURIComponent(a),d="login_check.php",f=lpLoginCheckResponse,e=lpLoginCheckError);""!=c&&(b+="&trustlabel="+encodeURIComponent(c));multifactor_getdata("wxsessid")&&(b+="&wxsessid="+encodeURIComponent(multifactor_getdata("wxsessid")));multifactor_getdata("type")&&(b+="&type="+encodeURIComponent(multifactor_getdata("type")));var g=multifactor_getdata("fromwebsite");console_log("server.js : Requesting "+d+" F");lpMakeRequest(base_url+
d,b,f,e,g)}else lpshowError("LoginError",!1,!0,!1,get_multifactor_disable_url(g_username,multifactor_getdata("type"))),loggedOut(!1,"multifactor_auth_error")}function multifactor_response(a,c){lpdbg("multifactor","in multifactor_response");"undefined"!=typeof a.callback?(lpdbg("multifactor","calling callback"),a.callback(c)):sendCS(a.tabid,c,a.docnum)}
function lpSetupMultifactorResponse(a,c,b){lpdbg("multifactor","setupmultifactorresponse: "+a.readyState);if(4==a.readyState){lpdbg("multifactor","setupmultifactorresponse: "+a.status);if(200==a.status&&(null!=a.responseXML&&null!=a.responseXML.documentElement)&&(a=a.responseXML.documentElement.getElementsByTagName("ok"),0<a.length)){var d=a[0].getAttribute("type");lpdbg("multifactor","setupmultifactorresponse: "+d);var f=a[0].getAttribute("hash");if("trueapi"==d)if("undefined"!=typeof b.password){if(have_binary_function("trueapi_store_default_login")){call_binary_function("trueapi_store_hash",
g_username,f,function(a){if(a){var c=function(a){a==f?call_binary_function("trueapi_store_default_login",g_username,b.password,f,function(a){a?(setsinglefactortype(d),"1"!=b.silent&&multifactor_response(b,{cmd:"setupsinglefactor",result:"done"})):lpSetupMultifactorError(b)}):lpSetupMultifactorError(b)};"1"==b.silent?c(f):call_binary_function("trueapi_get_hash",g_username,function(a){c(a)})}else lpSetupMultifactorError(b)});return}}else{if("1"!=b.silent&&have_binary_function("trueapi_store_hash")){call_binary_function("trueapi_store_hash",
g_username,f,function(a){a?call_binary_function("trueapi_get_hash",g_username,function(a){a==f?multifactor_response(b,{cmd:"setupmultifactor",result:"done"}):lpSetupMultifactorError(b)}):lpSetupMultifactorError(b)});return}}else if("vtapi"==d){if(have_binary_function("lpvt_store_data")){call_binary_function("lpvt_store_data",encodeURIComponent(g_username)+"|"+encodeURIComponent(b.password),gs("Swipe finger"),gs("Swipe your finger on the fingerprint sensor"),gs("Cancel"),gs("Swipe current user's finger"),
function(a){a?(setsinglefactortype(d),"1"!=b.silent&&multifactor_response(b,{cmd:"setupsinglefactor",result:"done"})):lpSetupMultifactorError(b)});return}}else if("validity"==d){if(have_binary_function("validity_store_data")){call_binary_function("validity_store_data",encodeURIComponent(g_username)+"|"+encodeURIComponent(b.password),gs("Swipe finger"),gs("Swipe your finger on the fingerprint sensor"),gs("Cancel"),function(a){a?(setsinglefactortype(d),"1"!=b.silent&&multifactor_response(b,{cmd:"setupsinglefactor",
result:"done"})):lpSetupMultifactorError(b)});return}}else if("winbio"==d){if(have_binary_function("winbio_store_data")){call_binary_function("winbio_has_fingerprints",function(a){lpdbg("multifactor","winbio_has_fingerprints: "+a);a?call_binary_function("winbio_store_data",encodeURIComponent(g_username)+"|"+encodeURIComponent(b.password),gs("Swipe finger"),gs("Swipe your finger on the fingerprint sensor"),gs("Cancel"),function(a){lpdbg("multifactor","winbio_store_data: "+a);a?(setsinglefactortype(d),
"1"!=b.silent&&(lpdbg("multifactor","calling multifactor_response"),multifactor_response(b,{cmd:"setupsinglefactor",result:"done"}))):lpSetupMultifactorError(b)}):(have_binary_function("winbio_launch_enrollment")&&call_binary_function("winbio_launch_enrollment"),"1"!=b.silent&&multifactor_response(b,{cmd:"setupsinglefactor",result:"notenrolled"}))});return}}else if("omnikey"==d){multifactor_response(b,{cmd:"setupsinglefactor",result:"done"});return}}lpSetupMultifactorError(b)}}
function lpSetupMultifactorError(a){1!=a.silent&&multifactor_response(a,{cmd:"undefined"!=typeof a.password?"setupsinglefactor":"setupmultifactor",result:"error"})}function get_multifactor_disable_url(a,c){return"multifactordisable.php?cmd=sendemail&username="+en(a)+"&type="+en(c)}function lp_StartLogin(a){console_log("server.js : lp_StartLogin fromlogincheckack="+a);g_loginstarted||(g_loginstarted=!0,a?(rsa_setpendingsharests(),lplogincheck("frompipes")):httptest())}
function can_chrome_do_math(){return"cf80cd8aed482d5d1527d7dc72fceff84e6326592848447d2dc0b0e87dfc9a90"!=SHA256("testing")?!1:!0}
function lpDownloadDataResponse(a,c,b){if(a&&200==a.status&&4==a.readyState){c="";a=a.responseText.split("\n");for(var d=0;d<a.length;d++)if(0==a[d].indexOf("ff_")){var f=a[d].indexOf("=");if(-1!=f){var e=a[d].substr(0,f),f=a[d].substr(f+1),f=CheckStringForObfuscation(e,"",f);c+=e+"="+f+"\n"}}else c+=a[d]+"\n";try{localStorage.setItem(b,c)}catch(g){L("Failed to setItem("+b+") e: "+g)}"ff.dat"==b?ApplyAllOverrides():"sites.dat"==b&&LoadSpecialSites()}}
function checkIterationsInDataFile(a){var c=get_key_iterations(g_username),b=a.substring(0,20);return 0==b.indexOf("iterations=")?(b=/iterations=(\d*);/.exec(b),1<b.length&&c==b[1]?a.substring(a.indexOf(";")+1):"iterationserror"):1!=c?"iterationserror":a}function prependIterations(a){var c=get_key_iterations(g_username);1<c&&(a="iterations="+c+";"+a);return a}
function checkIterationsReductionOk(a){var c=SHA256(g_username)+"_key_iter";return"undefined"!=typeof localStorage&&null!=localStorage.getItem(c)&&localStorage.getItem(c)>a&&g_checkiterationsreduction?confirm(gs("IterationsReduction")):!0};
